# coding: utf-8

"""
    Tekton

    Python SDK for Tekton Pipeline  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from tekton.models.v1beta1_condition_check_status import V1beta1ConditionCheckStatus  # noqa: F401,E501


class V1beta1PipelineRunConditionCheckStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'condition_name': 'str',
        'status': 'V1beta1ConditionCheckStatus'
    }

    attribute_map = {
        'condition_name': 'conditionName',
        'status': 'status'
    }

    def __init__(self, condition_name=None, status=None):  # noqa: E501
        """V1beta1PipelineRunConditionCheckStatus - a model defined in Swagger"""  # noqa: E501

        self._condition_name = None
        self._status = None
        self.discriminator = None

        if condition_name is not None:
            self.condition_name = condition_name
        if status is not None:
            self.status = status

    @property
    def condition_name(self):
        """Gets the condition_name of this V1beta1PipelineRunConditionCheckStatus.  # noqa: E501

        ConditionName is the name of the Condition  # noqa: E501

        :return: The condition_name of this V1beta1PipelineRunConditionCheckStatus.  # noqa: E501
        :rtype: str
        """
        return self._condition_name

    @condition_name.setter
    def condition_name(self, condition_name):
        """Sets the condition_name of this V1beta1PipelineRunConditionCheckStatus.

        ConditionName is the name of the Condition  # noqa: E501

        :param condition_name: The condition_name of this V1beta1PipelineRunConditionCheckStatus.  # noqa: E501
        :type: str
        """

        self._condition_name = condition_name

    @property
    def status(self):
        """Gets the status of this V1beta1PipelineRunConditionCheckStatus.  # noqa: E501

        Status is the ConditionCheckStatus for the corresponding ConditionCheck  # noqa: E501

        :return: The status of this V1beta1PipelineRunConditionCheckStatus.  # noqa: E501
        :rtype: V1beta1ConditionCheckStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this V1beta1PipelineRunConditionCheckStatus.

        Status is the ConditionCheckStatus for the corresponding ConditionCheck  # noqa: E501

        :param status: The status of this V1beta1PipelineRunConditionCheckStatus.  # noqa: E501
        :type: V1beta1ConditionCheckStatus
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1beta1PipelineRunConditionCheckStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1beta1PipelineRunConditionCheckStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
