# coding: utf-8

"""
    Tekton

    Python SDK for Tekton Pipeline  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from tekton.models.v1beta1_pipeline_run_condition_check_status import V1beta1PipelineRunConditionCheckStatus  # noqa: F401,E501
from tekton.models.v1beta1_task_run_status import V1beta1TaskRunStatus  # noqa: F401,E501


class V1beta1PipelineRunTaskRunStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'condition_checks': 'dict(str, V1beta1PipelineRunConditionCheckStatus)',
        'pipeline_task_name': 'str',
        'status': 'V1beta1TaskRunStatus'
    }

    attribute_map = {
        'condition_checks': 'conditionChecks',
        'pipeline_task_name': 'pipelineTaskName',
        'status': 'status'
    }

    def __init__(self, condition_checks=None, pipeline_task_name=None, status=None):  # noqa: E501
        """V1beta1PipelineRunTaskRunStatus - a model defined in Swagger"""  # noqa: E501

        self._condition_checks = None
        self._pipeline_task_name = None
        self._status = None
        self.discriminator = None

        if condition_checks is not None:
            self.condition_checks = condition_checks
        if pipeline_task_name is not None:
            self.pipeline_task_name = pipeline_task_name
        if status is not None:
            self.status = status

    @property
    def condition_checks(self):
        """Gets the condition_checks of this V1beta1PipelineRunTaskRunStatus.  # noqa: E501

        ConditionChecks maps the name of a condition check to its Status  # noqa: E501

        :return: The condition_checks of this V1beta1PipelineRunTaskRunStatus.  # noqa: E501
        :rtype: dict(str, V1beta1PipelineRunConditionCheckStatus)
        """
        return self._condition_checks

    @condition_checks.setter
    def condition_checks(self, condition_checks):
        """Sets the condition_checks of this V1beta1PipelineRunTaskRunStatus.

        ConditionChecks maps the name of a condition check to its Status  # noqa: E501

        :param condition_checks: The condition_checks of this V1beta1PipelineRunTaskRunStatus.  # noqa: E501
        :type: dict(str, V1beta1PipelineRunConditionCheckStatus)
        """

        self._condition_checks = condition_checks

    @property
    def pipeline_task_name(self):
        """Gets the pipeline_task_name of this V1beta1PipelineRunTaskRunStatus.  # noqa: E501

        PipelineTaskName is the name of the PipelineTask.  # noqa: E501

        :return: The pipeline_task_name of this V1beta1PipelineRunTaskRunStatus.  # noqa: E501
        :rtype: str
        """
        return self._pipeline_task_name

    @pipeline_task_name.setter
    def pipeline_task_name(self, pipeline_task_name):
        """Sets the pipeline_task_name of this V1beta1PipelineRunTaskRunStatus.

        PipelineTaskName is the name of the PipelineTask.  # noqa: E501

        :param pipeline_task_name: The pipeline_task_name of this V1beta1PipelineRunTaskRunStatus.  # noqa: E501
        :type: str
        """

        self._pipeline_task_name = pipeline_task_name

    @property
    def status(self):
        """Gets the status of this V1beta1PipelineRunTaskRunStatus.  # noqa: E501

        Status is the TaskRunStatus for the corresponding TaskRun  # noqa: E501

        :return: The status of this V1beta1PipelineRunTaskRunStatus.  # noqa: E501
        :rtype: V1beta1TaskRunStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this V1beta1PipelineRunTaskRunStatus.

        Status is the TaskRunStatus for the corresponding TaskRun  # noqa: E501

        :param status: The status of this V1beta1PipelineRunTaskRunStatus.  # noqa: E501
        :type: V1beta1TaskRunStatus
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1beta1PipelineRunTaskRunStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1beta1PipelineRunTaskRunStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
