
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-06T10:25:02-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1594252d90a2b063cbfd8266b5ca18137a187e3",
 "version": "2.6.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
