name: py3dep-dev
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - setuptools
  - pip
  - pygeoogc
  - pygeoutils
  - xarray
  - scipy
  - rasterio
  - shapely

  - dask
  - netCDF4
  - bottleneck

  - setuptools_scm
  - pytest-cov
  - pytest-xdist
  - pre-commit
  - codecov
  - coverage
  - pip:
    - numbagg
