#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['sfn_workflow_client']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

install_requires = \
['aenum>=2.1.0,<3', 'arrow>=0.12.1,<1', 'backoff>=1.8.0,<2', 'boto3']

setup(name='sfn_workflow_client',
      version='0.4.1',
      description='Enhanced, asyncio-compatible client for AWS Step Functions.',
      author='Jonathan Drake',
      author_email='jdrake@narrativescience.com',
      url='https://github.com/NarrativeScience/sfn-workflow-client',
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      python_requires='>=3.6,<4',
     )
