
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-14T10:28:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a0ee19230dc3d56485fd27d14bc4c027df63405",
 "version": "0.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
