# This file automatically generated by
#    /home/couchbase/jenkins/workspace/python/sdk/python-scripted-build-pipeline/couchbase-python-client/couchbase_version.py
# at
#    2020-08-11 20:35:05.798533
__version__ = '3.0.4'