# Generated by Django 2.2.4 on 2019-08-29 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election', '0002_auto_20190826_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaderToken',
            fields=[
                ('uid', models.CharField(blank=True, editable=False, max_length=500)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='API key')),
                ('election_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='election.ElectionDay')),
            ],
            options={
                'unique_together': {('election_day', 'slug')},
            },
        ),
    ]
