# Generated by Django 2.2.4 on 2019-08-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_loader', '0002_auto_20190829_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadertoken',
            name='key',
            field=models.CharField(blank=True, max_length=40, primary_key=True, serialize=False, verbose_name='API key'),
        ),
    ]
