image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - tests
  - release

pytest:
  stage: tests
  script:
    - python3 -m pip install -e .
    - python3 -m pip install -r setup/requirements/dev-requirements.txt
    - cp setup/other/systemctl.py /usr/bin/systemctl
    - chmod +x /usr/bin/systemctl
    - cd wizer/tests/
    - python3 -m pytest unit_tests -v
    - python3 -m pytest integration_tests -v

end2end:
  stage: tests
  script:
    - python3 -m pip install -e .
    - python3 -m pip install -r setup/requirements/dev-requirements.txt
    - wkz init
    - python3 -m pytest wizer/tests/end2end/ -v

pypi:
  stage: release
  cache: {}
  script:
    - pip install -U twine
    - python setup.py sdist
    - twine upload dist/*
  only:
    - master
  only:
    - tags
