version: '3.3'

services:
  django:
    container_name: workoutizer
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bash -xc "
      git checkout master
      && python manage.py collectstatic --no-input
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8001 --noreload
      "
    volumes:
      - .:/workoutizer
    ports:
      - "8001:8001"
    stdin_open: true
    tty: true
