from djangosubscribe.models.QuickEmailSubscriptionModel import QuickEmailSubscriptionModel
from djangosubscribe.models.BasicInformationModel import BasicInformationModel
from djangosubscribe.models.EducationalInformationModel import EducationalInformationModel
from djangosubscribe.models.WorkInformationModel import WorkInformationModel
from djangosubscribe.models.parentalInformationModel import ParentalInformationModel
from djangosubscribe.models.CategoryModel import CategoryModel