
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-06T17:55:12-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9137603d942a052027d310b5c12204e3883344d8",
 "version": "1.6.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
