
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='certbot-dns-onecloud',
    version='0.1.0',
    description='ONECLOUD DNS Authenticator plugin for Certbot',
    python_requires='<4,>=3.5',
    project_urls={"documentation": "https://github.com/porshkevich/certbot-dns-onecloud", "homepage": "https://github.com/porshkevich/certbot-dns-onecloud", "repository": "https://github.com/porshkevich/certbot-dns-onecloud"},
    author='NeoSonic',
    author_email='neosonic@inbox.ru',
    license='Apache License 2.0',
    classifiers=['Development Status :: 4 - Beta', 'Environment :: Plugins', 'Intended Audience :: System Administrators', 'License :: OSI Approved :: Apache Software License', 'Operating System :: POSIX :: Linux', 'Programming Language :: Python', 'Programming Language :: Python :: 3.5', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'Topic :: Internet :: WWW/HTTP', 'Topic :: Security', 'Topic :: System :: Installation/Setup', 'Topic :: System :: Networking', 'Topic :: System :: Systems Administration', 'Topic :: Utilities'],
    entry_points={"certbot.plugins": ["dns-onecloud = certbot_dns_onecloud.dns_onecloud:Authenticator"]},
    packages=['certbot_dns_onecloud'],
    package_dir={"": "."},
    package_data={},
    install_requires=['acme>=0.15.0', 'certbot>=0.15.0'],
    extras_require={"dev": ["coverage", "flake8", "mock==3.*,>=3.0.5", "pep8-naming", "pylama", "pylama-pylint", "pytest==4.*,>=4.0.0", "pytest-cov", "responses"]},
)
