
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-13T14:35:01+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a31ba8ffba89dbfa2aa99c96f59906daaff0b3a1",
 "version": "2.9.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
