
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-10T09:50:09+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed8ef56556ee0543a20b55d3bad34ea0e19ea9de",
 "version": "v1.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
