[tool.poetry]
name = "pipetoys"
version = "0.5.0"
description = "Pythonic function application."
license = "ISC"
readme = "README.md"
authors = ["SeparateRecords <me@rob.ac>"]

[tool.poetry.dependencies]
python = "^3.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
