<<: &shared
  language_name: Tagish
mappings:
  - display_name: Tagish to IPA
    mapping: tgx_to_ipa.json
    in_lang: tgx
    out_lang: tgx-ipa
    as_is: false
    norm_form: NFD
    case_sensitive: false
    authors:
      - Christopher Cox
    <<: *shared
  - display_name: Tagish IPA to English IPA
    mapping: tgx_ipa_to_eng_ipa.json
    in_lang: tgx-ipa
    out_lang: eng-ipa
    norm_form: NFD
    as_is: false
    case_sensitive: false
    authors:
      - Christopher Cox
    <<: *shared