
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-15T13:56:08-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "13b3b51087964d5e1a8c1cdd2495e07bdbe176b8",
 "version": "0.47.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
