#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pygitbucket']

package_data = \
{'': ['*']}

install_requires = \
['requests']

setup(name='pygitbucket',
      version='2020.8.12',
      description='This package enables you use the bitbucket REST-api using a simplified API',
      author='Edison Abahurire',
      author_email='abahedison@gmail.com',
      url='https://github.com/SimiCode/pygitbucket',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.6',
     )
