
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-11T17:42:47-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "03418ee037057aa85204f5a3feb2066cbb6a9b3e",
 "version": "0.47"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
