
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-12T13:54:33-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7702ea602188899ee9b0446a874a6a9b546b564d",
 "version": "0.47.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
