[tool.poetry]
name = "lassi"
version = "0.1.0"
description = "a"
authors = ["Julien Malard <julien.malard@mail.mcgill.ca>"] # ਜ਼ੂਲੀਏਂ ਮਲਾਰ
# homepage = "https://லஸ்ஸீ.பாரதம்"
repository = "https://github.com/lassi-samaaj/lassi"
documentation = "https://lassi.readthedocs.org"

keywords = ["lassi"]

classifiers = [
    "Topic :: Software Development :: Localization",
    "Topic :: Software Development :: Compilers"
]

# packages = [
#    { include = "lassi_es", from = "bld" },
#     { include = "lassi_fr", from = "bld" }
# ]

[tool.poetry.dependencies]
python = "^3.7"
lark-parser = "^0.8.5"
click = "^7.1.1"
ennikkai = "^1.2.1"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[tool.poetry.scripts]
poetry = 'poetry.console:run'

[tool.lassi]
src = "src"
dist = "dist"
lang = "த"  # langue - chiffres, langue - contenu

[tool.lassi.intl]
lang = ["fr", "kaq", "ਪੰ", "हिं", "es"]
fichier_trads = "மொ"
mono = false

# [build-system]
# requires = ["poetry>=0.12"]
# build-backend = "poetry.masonry.api"
