{
 "title": "Patching Status",
 "description": "Shows software patch status summary information",
 "tags": [ "patching" ],
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "${VAR_SERVER}" }
  ]
 },
 "panels": [
  {
   "title": "Total Updates Requested",
   "type": "singlestat",
   "description": "The total number of updates requested by all devices.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "extra_metrics_software_updates_by_state{state=\"Requested\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "# In-Progress Status (Assigned)",
   "type": "grafana-piechart-panel",
   "description": "Total number of in-progress updates across all devices.",
   "gridPos": { "h": 12, "w": 11, "x": 5, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "extra_metrics_software_updates_by_state{state!=\"Completed\", state!=\"Assigned\", state!=\"Requested\", state!=\"Unassigned\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Devices Affected",
   "type": "singlestat",
   "description": "Shows the number of devices affected by the outstanding or in-progress updates.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(extra_metrics_software_updates_remaining_by_device > 0) by (device_name))"
    }
   ]
  },
  {
   "title": "Total Updates Completed",
   "type": "singlestat",
   "description": "The total number of updates successfully deployed to devices.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "extra_metrics_software_updates_by_state{state=\"Completed\", instance=\"localhost:8000\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Total Updates Not Deployed",
   "type": "singlestat",
   "description": "The number of updates (across all devices) that are not currently planned for deployment.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "extra_metrics_software_updates_by_state{state=\"Unassigned\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "# Devices / Health",
   "type": "grafana-piechart-panel",
   "description": "Provides an overall health summary of all devices in the system.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "extra_metrics_per_device_compliance",
     "legendFormat": "{{compliance}}"
    }
   ]
  },
  {
   "title": "Total Updates Assigned",
   "type": "singlestat",
   "description": "The number of updates assigned (in-progress) across all devices.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(extra_metrics_software_updates_by_state{state=\"Assigned\"}) - sum(extra_metrics_software_updates_by_state{state=\"Completed\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "# Patches / Time",
   "type": "graph",
   "description": "Shows the number of devices over time, grouped by their patch status.  This is similar data as the pie chart above; but graphed over time.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "extra_metrics_software_updates_by_state{state!=\"Assigned\", state!=\"Requested\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Total Critical Updates",
   "type": "singlestat",
   "description": "Shows the total number of critical updates that are waiting to be deployed (or are in progress).",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(extra_metrics_software_updates_by_critical{is_critical=\"True\"})"
    }
   ]
  },
  {
   "title": "Total Other Updates",
   "type": "singlestat",
   "description": "Shows the total number of standard updates that are waiting to be deployed (or are in progress).",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(extra_metrics_software_updates_by_critical{is_critical=\"False\"})"
    }
   ]
  },
  {
   "title": "Top 10 Non Compliant Devices",
   "type": "table",
   "description": "Provides a list of the most non-compliant devices in terms of software updates.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(extra_metrics_software_updates_remaining_by_device{is_update_critical=\"False\"}) by (device_name, device_id)",
     "legendFormat": "{{device_name}}"
    },
    {
     "expr": "sum(extra_metrics_software_updates_remaining_by_device{is_update_critical=\"True\"}) by (device_name, device_id)",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Top Requested Patches",
   "type": "table",
   "description": "Shows a list of all the patches along with per device counts for not-started, in-progress and error/warnings state.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(extra_metrics_software_updates_by_popularity{state=\"Not Started\"}) by (update_name, update_id)",
     "legendFormat": "{{update_name}}"
    },
    {
     "expr": "sum(extra_metrics_software_updates_by_popularity{state=\"In Progress\"}) by (update_name, update_id)",
     "legendFormat": "{{update_name}}"
    },
    {
     "expr": "sum(extra_metrics_software_updates_by_popularity{state=\"Errors/Warnings\"}) by (update_name, update_id)",
     "legendFormat": "{{update_name}}"
    }
   ]
  }
 ]
}