
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-08T00:55:23-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "968ebf3befaf212a6b4332613d5aea39df38e7c1",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
