[tool.poetry]
name = "lonny_common_sql"
version = "0.1.0"
description = "A library for building inline SQL queries safely using python callables."
authors = ["tlonny <t@lonny.io>"]
readme = "README.md"
homepage = "https://lonny.io"
repository = "https://gitlab.com/lonny-common/sql"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pylama = "^7.7.1"
pyflakes = "^2.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"