
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-09T12:12:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd2b0679def88e363c16a9129e8182ac46caaa47",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
