
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-12T07:35:18-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "f37d8db18ab621ea47478c54e2471fd3ffc55d82",
 "version": "0.7.12a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
