[package]
name = "pyoxigraph"
version = "0.1.0-rc.1"
authors = ["Tpt <thomas@pellissier-tanon.fr>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["RDF", "SPARQL", "graph-database", "database"]
repository = "https://github.com/oxigraph/oxigraph/tree/master/python"
description = """
Python bindings of Oxigraph, a SPARQL database and RDF toolkit
"""
edition = "2018"

[lib]
crate-type = ["cdylib"]
name = "pyoxigraph"
doctest = false

[dependencies]
oxigraph = {version = "0.1.0-rc.1", features = ["sled"]}
pyo3 = {version = "0.11", features = ["extension-module"]}

[package.metadata.maturin]
classifier = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Rust",
    "Topic :: Database :: Database Engines/Servers"
]