[tool.poetry]
name = "kass-flow"
version = "0.2.6"
authors = ["Jón Levy <nonni@nonni.cc>"]
license = "MIT"
description = "Library to manage payments using the KASS API"
homepage = "https://github.com/busla/kass-flow"
readme = "README.rst"
include = ["kass_flow/py.typed"]

[tool.poetry.dependencies]
python = ">=3.6,<3.9"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
pylint = "^2.5.3"
black = "^19.10b0"
mypy = "^0.782"
pytest = "^6.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
