from djangosubscribe.signals.CreateBasicInformationSignal import CreateBasicInformationSignal
from djangosubscribe.signals.CreateEducationalInformationSignal import CreateEducationalInformationSignal
from djangosubscribe.signals.CreateWorkInformationSignal import CreateWorkInformationSignal
from djangosubscribe.signals.CreateParentalInformationSignal import CreateParentalInformationSignal