
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-13T09:40:23-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9cfd530759a1077718a38bdd85c335f3c12b35c1",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
