# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/config/filter/network/direct_response/v2/config.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from ......api.v2 import core as _____api_v2_core__


@dataclass
class Config(betterproto.Message):
    # Response data as a data source.
    response: _____api_v2_core__.DataSource = betterproto.message_field(1)
