---
project: DEFAULT_PROJECT
release: master
version: master
author: DEFAULT_AUTHOR
copyright: 2018, DEFAULT_PROJECT

needs_sphinx: "1.6.5"
extensions:
  - sphinx.ext.autodoc
  - sphinx.ext.doctest
  - sphinx.ext.intersphinx
  - sphinx.ext.todo
  - sphinx.ext.coverage
  - sphinx.ext.viewcode
  - sphinx_tabs.tabs
exclude_patterns:
  - .DS_Store
  - _build
  - Thumbs.db
todo_include_todos: false

html_theme: bootstrap
html_theme_options:
  bootswatch_theme: cerulean
  navbar_sidebarrel: false
  source_link_position: footer
