# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/filters/http/tap/v4alpha/tap.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .....common.tap import v4alpha as ____common_tap_v4_alpha__


@dataclass
class Tap(betterproto.Message):
    """Top level configuration for the tap filter."""

    # Common configuration for the HTTP tap filter.
    common_config: ____common_tap_v4_alpha__.CommonExtensionConfig = betterproto.message_field(
        1
    )
