[tool.poetry]
name = "xmind2case"
version = "1.0.8"
description = "xmind to csv"
authors = ["xuanke <zhouliwei1989@126.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "webtool"},
    { include = "xmind2case"}
]

# 添加清华镜像
[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true  # 设置清华镜像为默认回调, 以避免 poetry 在某些缺省操作里又回调到 pypi 仓库.

[tool.poetry.dependencies]
python = "^3.7"
xmind = "^1.2.0"
flask = "^1.1.2"
arrow = "^0.15.8"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
xmind2case = 'xmind2case.cli:cli_main'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

