# docs.yaml
name: Auto update docs for master branch
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.BUILD_DOCS_ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: html-site
        BUILD_SCRIPT: |
          apt-get install python3-pip -y &&
          pip3 install sphinx==1.7.5 &&  
          pip3 install sphinxcontrib-napoleon &&
          pip3 install numpy &&  
          pip3 install monty &&  
          pip3 install m2r &&
          python3 setup.py install &&  
          cd docs && make html && mv _build/html/  ../html-site && cd  ..
