[tool.poetry]
name = "spammer_py"
version = "0.1.2"
description = "Computer and email spammer"
authors = ["AndyZhou <AndyForever0108@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"
click = "^7.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
