[tool.poetry]
name = "lonny_common_pg"
version = "0.1.0"
description = "A quality-of-life wrapper for the psycopg2 connection object."
authors = ["tlonny <t@lonny.io>"]
readme = "README.md"
homepage = "https://lonny.io"
repository = "https://gitlab.com/lonny-common/pg"

[tool.poetry.dependencies]
python = "^3.8"
lonny_common_sql = "^0.1.0"
psycopg2-binary = "^2.8.5"

[tool.poetry.dev-dependencies]
pyflakes = "^2.2.0"
pylama = "^7.7.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
