__title__ = 'initme'
__package_name__ = 'initme'
__version__ = '0.2.0'
__description__ = "Create the __init__.py file in every single subdirectroy with a python folder"
__email__ = "george@cerebralab.com"
__author__ = 'George Hosu'
__github__ = 'https://github.com/George3d6/initme'
__pypi__ = 'https://pypi.org/project/initme/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2020 - George Hosu'
