# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-05 06:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_id', models.CharField(max_length=64, verbose_name='\u63a5\u6536\u8005ID')),
                ('from_id', models.CharField(max_length=64, verbose_name='\u53d1\u9001\u8005ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('type', models.CharField(choices=[(b'text', '\u6587\u672c'), (b'image', '\u56fe\u7247'), (b'shortvideo', '\u5c0f\u89c6\u9891'), (b'voice', '\u8bed\u97f3'), (b'video', '\u89c6\u9891'), (b'event', '\u4e8b\u4ef6'), (b'location', '\u5730\u7406\u4f4d\u7f6e')], default=b'text', max_length=16, verbose_name='\u7c7b\u522b')),
                ('msg_id', models.IntegerField(blank=True, null=True, verbose_name='\u7f16\u53f7')),
                ('content', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u6d88\u606f',
                'verbose_name_plural': '\u6d88\u606f',
            },
        ),
        migrations.CreateModel(
            name='OrderPrepayId',
            fields=[
                ('order_number', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='\u8ba2\u5355\u7f16\u53f7')),
                ('prepay_id', models.CharField(max_length=64, verbose_name='\u8ba2\u5355\u7f16\u53f7')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u9884\u4e0b\u5355\u53f7',
                'verbose_name_plural': '\u8ba2\u5355\u9884\u4e0b\u5355\u53f7',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('openid', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='openId')),
                ('unionid', models.CharField(blank=True, max_length=64, null=True, verbose_name='unionId')),
                ('nickname', models.CharField(max_length=64, verbose_name='\u6635\u79f0')),
                ('headimgurl', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5934\u50cf')),
                ('city', models.CharField(max_length=64, verbose_name='\u57ce\u5e02')),
                ('province', models.CharField(max_length=64, verbose_name='\u7701\u4efd')),
                ('longitude', models.FloatField(null=True, verbose_name='\u7ecf\u5ea6')),
                ('latitude', models.FloatField(null=True, verbose_name='\u7eac\u5ea6')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_wechat_user', to=settings.AUTH_USER_MODEL, verbose_name='\u7f51\u7ad9\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
    ]
