# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-23 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20180112_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='\u6027\u522b'),
        ),
    ]
