# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django_szuprefix.utils.modelutils


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='\u4e2d\u56fd', max_length=64, verbose_name='\u56fd\u5bb6'),
        ),
        migrations.AddField(
            model_name='user',
            name='groupid',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='\u5206\u7ec4ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='zh_CN', max_length=16, verbose_name='\u8bed\u8a00'),
        ),
        migrations.AddField(
            model_name='user',
            name='qr_scene',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='\u626b\u7801\u573a\u666f'),
        ),
        migrations.AddField(
            model_name='user',
            name='qr_scene_str',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='\u626b\u7801\u573a\u666f\u63cf\u8ff0'),
        ),
        migrations.AddField(
            model_name='user',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe',
            field=models.BooleanField(default=True, verbose_name='\u8ba2\u9605'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe_scene',
            field=models.CharField(blank=True, default='ADD_SCENE_QR_CODE', max_length=32, verbose_name='\u5173\u6ce8\u6e20\u9053'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u8ba2\u9605\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tagid_list',
            field=django_szuprefix.utils.modelutils.JSONField(blank=True, default=[], verbose_name='\u6807\u7b7eID\u5217\u8868'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', '\u7537'), ('2', '\u5973'), ('0', '\u672a\u77e5')], max_length=2, null=True, verbose_name='\u6027\u522b'),
        ),
    ]
