# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-13 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_auto_20180406_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='\u7f16\u53f7'),
        ),
    ]
