# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-19 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_auto_20190313_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9'),
        ),
    ]
