# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-06 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0006_auto_20190619_0225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-subscribe_time',), 'verbose_name': '\u7528\u6237', 'verbose_name_plural': '\u7528\u6237'},
        ),
        migrations.AlterField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribe_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u8ba2\u9605\u65f6\u95f4'),
        ),
    ]
