# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-08 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0007_auto_20191006_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u57ce\u5e02'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='\u4e2d\u56fd', max_length=128, verbose_name='\u56fd\u5bb6'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7701\u4efd'),
        ),
    ]
