
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-12T05:59:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ffdb81688991456863bf540d960e3a01f2ab9910",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
