tech:
    name: generic
    cache_url:
    with_settings_label: False
    add_pins: True
    wg_expanded_width : 2.5
    taper_length: 35.0
    grid_unit: 1e-6
    grid_resolution: 1e-9
    bend_radius: 10.0
