# coding: utf-8

"""
    Tekton

    Python SDK for Tekton Pipeline  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from tekton.models.v1beta1_cloud_event_delivery_state import V1beta1CloudEventDeliveryState  # noqa: F401,E501


class V1beta1CloudEventDelivery(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'V1beta1CloudEventDeliveryState',
        'target': 'str'
    }

    attribute_map = {
        'status': 'status',
        'target': 'target'
    }

    def __init__(self, status=None, target=None):  # noqa: E501
        """V1beta1CloudEventDelivery - a model defined in Swagger"""  # noqa: E501

        self._status = None
        self._target = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if target is not None:
            self.target = target

    @property
    def status(self):
        """Gets the status of this V1beta1CloudEventDelivery.  # noqa: E501


        :return: The status of this V1beta1CloudEventDelivery.  # noqa: E501
        :rtype: V1beta1CloudEventDeliveryState
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this V1beta1CloudEventDelivery.


        :param status: The status of this V1beta1CloudEventDelivery.  # noqa: E501
        :type: V1beta1CloudEventDeliveryState
        """

        self._status = status

    @property
    def target(self):
        """Gets the target of this V1beta1CloudEventDelivery.  # noqa: E501

        Target points to an addressable  # noqa: E501

        :return: The target of this V1beta1CloudEventDelivery.  # noqa: E501
        :rtype: str
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this V1beta1CloudEventDelivery.

        Target points to an addressable  # noqa: E501

        :param target: The target of this V1beta1CloudEventDelivery.  # noqa: E501
        :type: str
        """

        self._target = target

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1beta1CloudEventDelivery, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1beta1CloudEventDelivery):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
