[tool.poetry]
name = "pyflowcl"
version = "0.1.0"
description = "Cliente para comunicacion con API de flow.cl"
authors = ["Mario Hernandez <yo@mariofix.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-pep8 = "^1.0.6"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
