[tool.poetry]
name = "willing-zg"
version = "1.3.0"
description = ""
readme = "README.md"
authors = ["Bequest, Inc. <oss@willing.com>"]

[tool.poetry.dependencies]
python = "^3.7"
zygoat = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.7.9"
flake8-black = "^0.1.1"

[tool.black]
line-length = 95
target-version = ['py37']
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
