# coding: utf-8

"""
    Tekton

    Python SDK for Tekton Pipeline  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tekton
from tekton.models.v1beta1_cluster_task import V1beta1ClusterTask  # noqa: E501
from tekton.rest import ApiException


class TestV1beta1ClusterTask(unittest.TestCase):
    """V1beta1ClusterTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1ClusterTask(self):
        """Test V1beta1ClusterTask"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tekton.models.v1beta1_cluster_task.V1beta1ClusterTask()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
