---
#
####################################################
#
# weblate_server_email and weblate_default_from_email as
# described in the weblate documentation as SERVER_EMAIL and
# DEFAULT_FROM_EMAIL respectively.
#
# https://docs.weblate.org/en/latest/admin/install.html#production-email
#
weblate_server_email: "admin@{{ domain }}"
weblate_default_from_email: "admin@{{ domain }}"
#
####################################################
#
# weblate_admin_email and weblate_admin_password as
# described in the weblate documentation as WEBLATE_ADMIN_NAME
# and WEBLATE_ADMIN_EMAIL
#
# https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-WEBLATE_ADMIN_EMAIL
#
weblate_admin_email: "admin@{{ domain }}"
weblate_admin_password: admin

weblate_version: 4.0.4-1
