
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-12T13:47:03-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd4d9037787d9fa1bba06a8fede6edd3a2b411da",
 "version": "1.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
