# -*- coding: utf-8 -*-
# cython: language_level=3
# Copyright (c) 2020 Nekokatt
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# This stubfile is generated by Hikari's deploy script as a workaround
# for our design not working correctly with MyPy's --strict flag. By
# explicitly generating this stub, MyPy no longer gets confused by what
# members are re-exported by package level init scripts. This lets you
# type check as strictly as possible and still get correct results.
#
# For all other purposes, you can completely ignore this file!


from hikari.models.applications import *
from hikari.models.audit_logs import *
from hikari.models.channels import *
from hikari.models.colors import *
from hikari.models.colours import *
from hikari.models.embeds import *
from hikari.models.emojis import *
from hikari.models.gateway import *
from hikari.models.guilds import *
from hikari.models.intents import *
from hikari.models.invites import *
from hikari.models.messages import *
from hikari.models.permissions import *
from hikari.models.presences import *
from hikari.models.users import *
from hikari.models.voices import *
from hikari.models.webhooks import *

# Names in __all__ with no definition:
#   Activity
#   ActivityAssets
#   ActivityFlag
#   ActivityParty
#   ActivitySecret
#   ActivityTimestamps
#   ActivityType
#   Application
#   Attachment
#   AuditLog
#   AuditLogChange
#   AuditLogChangeKey
#   AuditLogEntry
#   AuditLogEventType
#   BaseAuditLogEntryInfo
#   ChannelOverwriteEntryInfo
#   ChannelType
#   ClientStatus
#   Color
#   Colorish
#   Colour
#   Colourish
#   ConnectionVisibility
#   CustomEmoji
#   Embed
#   EmbedAuthor
#   EmbedField
#   EmbedFooter
#   EmbedImage
#   EmbedProvider
#   EmbedResource
#   EmbedResourceWithProxy
#   EmbedVideo
#   Emoji
#   Emojiish
#   GatewayBot
#   GatewayGuild
#   GroupPrivateTextChannel
#   Guild
#   GuildCategory
#   GuildChannel
#   GuildExplicitContentFilterLevel
#   GuildFeature
#   GuildFeatureish
#   GuildMFALevel
#   GuildMemberBan
#   GuildMessageNotificationsLevel
#   GuildNewsChannel
#   GuildPremiumTier
#   GuildPreview
#   GuildStoreChannel
#   GuildSystemChannelFlag
#   GuildTextChannel
#   GuildVerificationLevel
#   GuildVoiceChannel
#   GuildWidget
#   Integration
#   IntegrationAccount
#   IntegrationExpireBehaviour
#   Intent
#   Invite
#   InviteGuild
#   InviteWithMetadata
#   Inviteish
#   KnownCustomEmoji
#   Member
#   MemberDisconnectEntryInfo
#   MemberMoveEntryInfo
#   MemberPresence
#   MemberPruneEntryInfo
#   Message
#   MessageActivity
#   MessageActivityType
#   MessageBulkDeleteEntryInfo
#   MessageCrosspost
#   MessageDeleteEntryInfo
#   MessageFlag
#   MessagePinEntryInfo
#   MessageType
#   OAuth2Scope
#   OwnConnection
#   OwnGuild
#   OwnUser
#   PartialChannel
#   PartialGuild
#   PartialIntegration
#   PartialMessage
#   PartialRole
#   PartialUser
#   Permission
#   PermissionOverwrite
#   PermissionOverwriteType
#   PremiumType
#   PrivateTextChannel
#   RESTGuild
#   Reaction
#   RichActivity
#   Role
#   SessionStartLimit
#   Status
#   TargetUserType
#   Team
#   TeamMember
#   TeamMembershipState
#   TextChannel
#   UnavailableGuild
#   UnicodeEmoji
#   UnrecognisedAuditLogEntryInfo
#   User
#   UserFlag
#   VanityURL
#   VoiceRegion
#   VoiceRegionish
#   VoiceState
#   Webhook
#   WebhookType
