[tool.poetry]
name = "reqs"
version = "0.0.2"
description = ""
authors = ["Kirill Plotnikov <init@pltnk.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
reqs = 'reqs.reqs:main'
