[tool.poetry]
name = "zxbasic"
version = "1.12.0"
description = "Boriel's ZX BASIC Compiler"
authors = ["Jose Rodriguez <boriel@gmail.com>"]
license = "GPL-3.0-or-later"
documentation = "https://zxbasic.readthedocs.io"
repository = "https://github.com/boriel/zxbasic"
homepage = "http://zxbasic.net"
readme = "README.md"

classifiers = [
        # How mature is this project? Common values are
        #   3 - Alpha
        #   4 - Beta
        #   5 - Production/Stable
        'Development Status :: 5 - Production/Stable',

        # Indicate who your project is intended for
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',

        # Pick your license as you wish (should match "license" above)
        'License :: OSI Approved :: GNU Affero General Public License v3',

        # Specify the Python versions you support here. In particular, ensure
        # that you indicate whether you support Python 2, Python 3 or both.
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.8',
        ]

keywords = ['compiler', 'zxspectrum', 'BASIC', 'z80']  # arbitrary keywords

packages = [
    { include = "api" },
    { include = "arch/**/*"},
    { include = "ast_" },
    { include = "outfmt" },
    { include = "parsetab" },
    { include = "ply" },
    { include = "symbols" },
    { include = "libzxbc" },
    { include = "libzxbasm" },
    { include = "libzxbpp" },
]

include = [
    'library/**/*',
    'library-asm/**/*'
]


[tool.poetry.scripts]
zxb = 'libzxbc.zxb:main'
zxbc = 'libzxbc.zxb:main'
zxbasm = 'libzxbasm.zxbasm:main'
zxbpp = 'libzxbpp.zxbpp:entry_point'

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
tox = "^3.15.1"
flake8 = "^3.8.2"
pytest = "^5.4.2"
pytest-timeout = "^1.3.4"
bump2version = "^1.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
