[tool.black]
line-length = 120
target-version = ['py36']

[tool.pytest.ini_options]
minversion = "6.0"
norecursedirs = ".* build dist *.egg-info install ENV"
addopts = "-v --tb=short --doctest-glob=''"

[tool.poetry]
name = "quaternionic"
version = "0.0.1a3"
license = "MIT"
description = "Interpret numpy arrays as quaternion arrays with numba acceleration"
readme = "README.md"
authors = ["Michael Boyle <michael.oliver.boyle@gmail.com>"]
homepage = "https://github.com/moble/quaternionic"

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.13"
scipy = "^1.0"
numba = "^0.50"

[tool.poetry.dev-dependencies]
pytest = "^6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
