# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/config/filter/http/on_demand/v2/on_demand.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class OnDemand(betterproto.Message):
    pass
