# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/filters/http/on_demand/v3/on_demand.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class OnDemand(betterproto.Message):
    pass
