# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/filters/http/dynamo/v3/dynamo.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Dynamo(betterproto.Message):
    """Dynamo filter config."""

    pass
