[tool.poetry]
name = "PyROAST"
version = "0.1.0"
description = "Reserved name"
authors = ["Kamuish <andremiguel952@gmail.com>"]
packages = [
    { include = "pyROAST"},
]
[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
