language: python
dist: bionic
os: linux

branches:
  except:
    - /^dependabot-.*$/

addons:
  apt:
    packages:
    - libproj-dev
    - libgeos-dev

git:
  depth: 150

python:
  - 3.8
  - 3.7
  - 3.6

cache:
  - pip

env:
  global:
    - GH_PAGES_DIR="$HOME/gh-pages"
    - VERSIONS="Current.txt"
  jobs:
    - TASK="coverage"
    - TASK="docs"

jobs:
  include:
    - python: 3.6
      env:
        - VERSIONS="Minimum"
        - TASK="coverage"
    - python: "3.8-dev"
      env:
        - VERSIONS="Prerelease"
        - GIT_VERSIONS="git+git://github.com/hgrecco/pint@master#egg=pint git+git://github.com/pydata/xarray@master#egg=xarray"
    - python: "3.8-dev"
      env:
        - TASK="docs"
        - VERSIONS="Prerelease"
        - GIT_VERSIONS="git+git://github.com/hgrecco/pint@master#egg=pint git+git://github.com/pydata/xarray@master#egg=xarray"
  allow_failures:
    - python: "3.8-dev"

before_install:
  # We hard-code the sphinx_rtd_theme to lock in our build with patch for
  # version chooser
  - python -m pip install --upgrade pip setuptools
  - python -m pip install --no-binary ":all:" shapely
  # Needed in order to build CartoPy--it needs it installed first
  - python -m pip install -c ci/${VERSIONS} numpy
  - if [[ $TASK == "docs" ]]; then
      python -m pip install -f https://unidata-python.s3.amazonaws.com/wheelhouse/index.html sphinx_rtd_theme==0.2.5b1.post1 -c ci/${VERSIONS};
      python -m pip install -r ci/doc_requirements.txt -r ci/extra_requirements.txt -c ci/${VERSIONS} ${GIT_VERSIONS};
    else
      python -m pip install -r ci/test_requirements.txt -r ci/extra_requirements.txt -c ci/${VERSIONS} ${GIT_VERSIONS};
    fi;

install:
  - python -m pip install . -c ci/${VERSIONS}

script:
  - export TEST_DATA_DIR=${TRAVIS_BUILD_DIR}/staticdata;
  - export NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=1;
  - if [[ $TASK == "docs" ]]; then
      pushd docs;
      make clean overridecheck html linkcheck O=-W;
      export DOC_BUILD_RESULT=$?;
      popd;
      if [[ $DOC_BUILD_RESULT -ne 0 ]]; then
        false;
      fi;
    else
      python -m pytest --mpl -W error::metpy.deprecation.MetpyDeprecationWarning --cov=metpy --cov=tests;
    fi

after_script:
  - if [[ $TASK != "coverage" ]]; then
      pip install codecov codacy-coverage;
      coverage xml;
      codecov -X gcov -f coverage.xml -e TRAVIS_PYTHON_VERSION;
      python-codacy-coverage -r coverage.xml;
    fi

before_deploy:
  # Remove unused, unminified javascript from sphinx
  - if [[ $TASK == "docs" ]]; then
      rm -f docs/build/html/_static/jquery-*.js;
      rm -f docs/build/html/_static/underscore-*.js;
      rm -f docs/build/html/.buildinfo;
    fi

deploy:
  - provider: pypi
    username: __token__
    distributions: sdist bdist_wheel
    on:
      repo: Unidata/MetPy
      python: 3.7
      condition: '$TASK != "docs"'
      tags: true
  - provider: script
    script: ci/deploy_docs.sh
    skip_cleanup: true
    on:
      all_branches: true
      python: 3.7
      condition: '$TASK == "docs"'
