[tool.poetry]
name = "senpai"
version = "0.1.0"
description = "Notices you"
authors = ["sangarshanan <sangarshanan1998@gmail.com>"]
maintainers = ["sangarshanan <sangarshanan1998@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
loguru = "*"
psutil = "*"

[tool.poetry.dev-dependencies]
pytest = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
