# coding: utf-8

"""
    Tekton

    Python SDK for Tekton Pipeline  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class V1beta1WorkspaceDeclaration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'mount_path': 'str',
        'name': 'str',
        'read_only': 'bool'
    }

    attribute_map = {
        'description': 'description',
        'mount_path': 'mountPath',
        'name': 'name',
        'read_only': 'readOnly'
    }

    def __init__(self, description=None, mount_path=None, name=None, read_only=None):  # noqa: E501
        """V1beta1WorkspaceDeclaration - a model defined in Swagger"""  # noqa: E501

        self._description = None
        self._mount_path = None
        self._name = None
        self._read_only = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if mount_path is not None:
            self.mount_path = mount_path
        self.name = name
        if read_only is not None:
            self.read_only = read_only

    @property
    def description(self):
        """Gets the description of this V1beta1WorkspaceDeclaration.  # noqa: E501

        Description is an optional human readable description of this volume.  # noqa: E501

        :return: The description of this V1beta1WorkspaceDeclaration.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this V1beta1WorkspaceDeclaration.

        Description is an optional human readable description of this volume.  # noqa: E501

        :param description: The description of this V1beta1WorkspaceDeclaration.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def mount_path(self):
        """Gets the mount_path of this V1beta1WorkspaceDeclaration.  # noqa: E501

        MountPath overrides the directory that the volume will be made available at.  # noqa: E501

        :return: The mount_path of this V1beta1WorkspaceDeclaration.  # noqa: E501
        :rtype: str
        """
        return self._mount_path

    @mount_path.setter
    def mount_path(self, mount_path):
        """Sets the mount_path of this V1beta1WorkspaceDeclaration.

        MountPath overrides the directory that the volume will be made available at.  # noqa: E501

        :param mount_path: The mount_path of this V1beta1WorkspaceDeclaration.  # noqa: E501
        :type: str
        """

        self._mount_path = mount_path

    @property
    def name(self):
        """Gets the name of this V1beta1WorkspaceDeclaration.  # noqa: E501

        Name is the name by which you can bind the volume at runtime.  # noqa: E501

        :return: The name of this V1beta1WorkspaceDeclaration.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V1beta1WorkspaceDeclaration.

        Name is the name by which you can bind the volume at runtime.  # noqa: E501

        :param name: The name of this V1beta1WorkspaceDeclaration.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def read_only(self):
        """Gets the read_only of this V1beta1WorkspaceDeclaration.  # noqa: E501

        ReadOnly dictates whether a mounted volume is writable. By default this field is false and so mounted volumes are writable.  # noqa: E501

        :return: The read_only of this V1beta1WorkspaceDeclaration.  # noqa: E501
        :rtype: bool
        """
        return self._read_only

    @read_only.setter
    def read_only(self, read_only):
        """Sets the read_only of this V1beta1WorkspaceDeclaration.

        ReadOnly dictates whether a mounted volume is writable. By default this field is false and so mounted volumes are writable.  # noqa: E501

        :param read_only: The read_only of this V1beta1WorkspaceDeclaration.  # noqa: E501
        :type: bool
        """

        self._read_only = read_only

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1beta1WorkspaceDeclaration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1beta1WorkspaceDeclaration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
