
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-07T15:55:36+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "1092ee63f1b41afad024327db9408adf7c7d2252",
 "version": "0.0.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
