# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/filters/listener/http_inspector/v3/http_inspector.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class HttpInspector(betterproto.Message):
    pass
