[tool.poetry]
name = "snf_simple"
version = "0.1.0"
description = "Similarity Network Fusion (SNF) python implementation"
authors = ["fmakdemir <fmakdemir@users.noreply.github.com>"]
license = "LGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.19.1"
scikit-learn = "^0.23.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
