# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: distill_discovery.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='distill_discovery.proto',
  package='paddle_edl.distill',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x17\x64istill_discovery.proto\x12\x12paddle_edl.distill\x1a\x19google/protobuf/any.proto\"N\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12%\n\x07\x64\x61tails\x18\x03 \x03(\x0b\x32\x14.google.protobuf.Any\"[\n\x0fRegisterRequest\x12\x0e\n\x06\x63lient\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x13\n\x0brequire_num\x18\x03 \x01(\x05\x12\r\n\x05token\x18\x04 \x01(\t\"N\n\x10HeartBeatRequest\x12\x0e\n\x06\x63lient\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x04\x12\x19\n\x11\x64iscovery_version\x18\x03 \x01(\x04\"\x8e\x01\n\x08Response\x12*\n\x06status\x18\x01 \x01(\x0b\x32\x1a.paddle_edl.distill.Status\x12\x0f\n\x07version\x18\x02 \x01(\x04\x12\x19\n\x11\x64iscovery_version\x18\x03 \x01(\x04\x12\x0f\n\x07servers\x18\x04 \x03(\t\x12\x19\n\x11\x64iscovery_servers\x18\x05 \x03(\t*\xa3\x01\n\x04\x43ode\x12\x06\n\x02OK\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x0c\n\x08NO_READY\x10\x02\x12\x0c\n\x08REDIRECT\x10\x03\x12\x14\n\x10INVALID_ARGUMENT\x10\x04\x12\x14\n\x10\x41LREADY_REGISTER\x10\x05\x12\x1a\n\x16REGISTER_OTHER_SERVICE\x10\x06\x12\x10\n\x0cUNREGISTERED\x10\x07\x12\x10\n\x0cUNAUTHORIZED\x10\x08\x32\xb6\x01\n\x10\x44iscoveryService\x12O\n\x08Register\x12#.paddle_edl.distill.RegisterRequest\x1a\x1c.paddle_edl.distill.Response\"\x00\x12Q\n\tHeartBeat\x12$.paddle_edl.distill.HeartBeatRequest\x1a\x1c.paddle_edl.distill.Response\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])

_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='paddle_edl.distill.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_READY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REDIRECT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_ARGUMENT', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALREADY_REGISTER', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REGISTER_OTHER_SERVICE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNREGISTERED', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNAUTHORIZED', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=473,
  serialized_end=636,
)
_sym_db.RegisterEnumDescriptor(_CODE)

Code = enum_type_wrapper.EnumTypeWrapper(_CODE)
OK = 0
UNKNOWN = 1
NO_READY = 2
REDIRECT = 3
INVALID_ARGUMENT = 4
ALREADY_REGISTER = 5
REGISTER_OTHER_SERVICE = 6
UNREGISTERED = 7
UNAUTHORIZED = 8



_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='paddle_edl.distill.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='paddle_edl.distill.Status.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='paddle_edl.distill.Status.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datails', full_name='paddle_edl.distill.Status.datails', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=152,
)


_REGISTERREQUEST = _descriptor.Descriptor(
  name='RegisterRequest',
  full_name='paddle_edl.distill.RegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='paddle_edl.distill.RegisterRequest.client', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_name', full_name='paddle_edl.distill.RegisterRequest.service_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='require_num', full_name='paddle_edl.distill.RegisterRequest.require_num', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='paddle_edl.distill.RegisterRequest.token', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=245,
)


_HEARTBEATREQUEST = _descriptor.Descriptor(
  name='HeartBeatRequest',
  full_name='paddle_edl.distill.HeartBeatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='paddle_edl.distill.HeartBeatRequest.client', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='paddle_edl.distill.HeartBeatRequest.version', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='discovery_version', full_name='paddle_edl.distill.HeartBeatRequest.discovery_version', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=325,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='paddle_edl.distill.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='paddle_edl.distill.Response.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='paddle_edl.distill.Response.version', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='discovery_version', full_name='paddle_edl.distill.Response.discovery_version', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='servers', full_name='paddle_edl.distill.Response.servers', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='discovery_servers', full_name='paddle_edl.distill.Response.discovery_servers', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=470,
)

_STATUS.fields_by_name['datails'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_RESPONSE.fields_by_name['status'].message_type = _STATUS
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['RegisterRequest'] = _REGISTERREQUEST
DESCRIPTOR.message_types_by_name['HeartBeatRequest'] = _HEARTBEATREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.enum_types_by_name['Code'] = _CODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'distill_discovery_pb2'
  # @@protoc_insertion_point(class_scope:paddle_edl.distill.Status)
  })
_sym_db.RegisterMessage(Status)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'distill_discovery_pb2'
  # @@protoc_insertion_point(class_scope:paddle_edl.distill.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

HeartBeatRequest = _reflection.GeneratedProtocolMessageType('HeartBeatRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATREQUEST,
  '__module__' : 'distill_discovery_pb2'
  # @@protoc_insertion_point(class_scope:paddle_edl.distill.HeartBeatRequest)
  })
_sym_db.RegisterMessage(HeartBeatRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'distill_discovery_pb2'
  # @@protoc_insertion_point(class_scope:paddle_edl.distill.Response)
  })
_sym_db.RegisterMessage(Response)



_DISCOVERYSERVICE = _descriptor.ServiceDescriptor(
  name='DiscoveryService',
  full_name='paddle_edl.distill.DiscoveryService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=639,
  serialized_end=821,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='paddle_edl.distill.DiscoveryService.Register',
    index=0,
    containing_service=None,
    input_type=_REGISTERREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HeartBeat',
    full_name='paddle_edl.distill.DiscoveryService.HeartBeat',
    index=1,
    containing_service=None,
    input_type=_HEARTBEATREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISCOVERYSERVICE)

DESCRIPTOR.services_by_name['DiscoveryService'] = _DISCOVERYSERVICE

# @@protoc_insertion_point(module_scope)
