# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import distill_discovery_pb2 as distill__discovery__pb2


class DiscoveryServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/paddle_edl.distill.DiscoveryService/Register',
                request_serializer=distill__discovery__pb2.RegisterRequest.SerializeToString,
                response_deserializer=distill__discovery__pb2.Response.FromString,
                )
        self.HeartBeat = channel.unary_unary(
                '/paddle_edl.distill.DiscoveryService/HeartBeat',
                request_serializer=distill__discovery__pb2.HeartBeatRequest.SerializeToString,
                response_deserializer=distill__discovery__pb2.Response.FromString,
                )


class DiscoveryServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartBeat(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=distill__discovery__pb2.RegisterRequest.FromString,
                    response_serializer=distill__discovery__pb2.Response.SerializeToString,
            ),
            'HeartBeat': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartBeat,
                    request_deserializer=distill__discovery__pb2.HeartBeatRequest.FromString,
                    response_serializer=distill__discovery__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'paddle_edl.distill.DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiscoveryService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/paddle_edl.distill.DiscoveryService/Register',
            distill__discovery__pb2.RegisterRequest.SerializeToString,
            distill__discovery__pb2.Response.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HeartBeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/paddle_edl.distill.DiscoveryService/HeartBeat',
            distill__discovery__pb2.HeartBeatRequest.SerializeToString,
            distill__discovery__pb2.Response.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
