name: dstoolbox
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - intel-openmp=2019.4
  - joblib=0.14.1
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=9.1.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1d
  - pandas=1.0.3
  - pip=19.3.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - readline=7.0
  - scikit-learn=0.23.1
  - scipy=1.3.2
  - setuptools=44.0.0
  - six=1.13.0
  - sqlite=3.30.1
  - tk=8.6.8
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
