
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-07-29T11:05:59-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4bf73c76c424b22c32cc19aa00539f6f4dd348a9",
 "version": "4.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
