# -*- coding: utf-8 -*-
# cython: language_level=3
# Copyright (c) 2020 Nekokatt
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# This stubfile is generated by Hikari's deploy script as a workaround
# for our design not working correctly with MyPy's --strict flag. By
# explicitly generating this stub, MyPy no longer gets confused by what
# members are re-exported by package level init scripts. This lets you
# type check as strictly as possible and still get correct results.
#
# For all other purposes, you can completely ignore this file!


from hikari.events.base_events import Event as Event
from hikari.events.base_events import ExceptionEvent as ExceptionEvent
from hikari.events.channel_events import *
from hikari.events.guild_events import *
from hikari.events.lifetime_events import *
from hikari.events.member_events import *
from hikari.events.message_events import *
from hikari.events.reaction_events import *
from hikari.events.role_events import *
from hikari.events.shard_events import *
from hikari.events.typing_events import *
from hikari.events.user_events import *
from hikari.events.voice_events import *

# Names in __all__ with no definition:
#   BanCreateEvent
#   BanDeleteEvent
#   BanEvent
#   ChannelCreateEvent
#   ChannelDeleteEvent
#   ChannelEvent
#   ChannelUpdateEvent
#   EmojisUpdateEvent
#   GuildAvailableEvent
#   GuildChannelCreateEvent
#   GuildChannelDeleteEvent
#   GuildChannelEvent
#   GuildChannelUpdateEvent
#   GuildLeaveEvent
#   GuildMessageBulkDeleteEvent
#   GuildMessageCreateEvent
#   GuildMessageDeleteEvent
#   GuildMessageEvent
#   GuildMessageUpdateEvent
#   GuildPinsUpdateEvent
#   GuildReactionAddEvent
#   GuildReactionDeleteAllEvent
#   GuildReactionDeleteEmojiEvent
#   GuildReactionDeleteEvent
#   GuildReactionEvent
#   GuildTypingEvent
#   GuildUnavailableEvent
#   GuildUpdateEvent
#   GuildVisibilityEvent
#   IntegrationsUpdateEvent
#   InviteCreateEvent
#   InviteDeleteEvent
#   MemberChunkEvent
#   MemberCreateEvent
#   MemberDeleteEvent
#   MemberEvent
#   MemberUpdateEvent
#   MessageBulkDeleteEvent
#   MessageCreateEvent
#   MessageDeleteEvent
#   MessageEvent
#   MessageUpdateEvent
#   MessagesEvent
#   OwnUserUpdateEvent
#   PinsUpdateEvent
#   PresenceUpdateEvent
#   PrivateChannelCreateEvent
#   PrivateChannelDeleteEvent
#   PrivateChannelEvent
#   PrivateChannelUpdateEvent
#   PrivateMessageCreateEvent
#   PrivateMessageDeleteEvent
#   PrivateMessageEvent
#   PrivateMessageUpdateEvent
#   PrivatePinsUpdateEvent
#   PrivateReactionAddEvent
#   PrivateReactionDeleteAllEvent
#   PrivateReactionDeleteEmojiEvent
#   PrivateReactionDeleteEvent
#   PrivateReactionEvent
#   PrivateTypingEvent
#   ReactionAddEvent
#   ReactionDeleteAllEvent
#   ReactionDeleteEmojiEvent
#   ReactionDeleteEvent
#   ReactionEvent
#   RoleCreateEvent
#   RoleDeleteEvent
#   RoleEvent
#   RoleUpdateEvent
#   ShardConnectedEvent
#   ShardDisconnectedEvent
#   ShardEvent
#   ShardReadyEvent
#   ShardResumedEvent
#   ShardStateEvent
#   StartedEvent
#   StartingEvent
#   StoppedEvent
#   StoppingEvent
#   TypingEvent
#   VoiceEvent
#   VoiceServerUpdateEvent
#   VoiceStateUpdateEvent
#   WebhookUpdateEvent
