[tool.black]
skip-string-normalization = true

[tool.poetry]
name = "vcspull"
version = "1.4.3"
description = "synchronize your repos and forks via declarative yaml/json file(s)"
license = "MIT"
authors = ["Tony Narlock <tony@git-pull.com>"]

[tool.poetry.dependencies]
python = "~2.7 || ^3.5"
click = ">=7<8"
kaptan = "*"
libvcs = "^0.4.4"
colorama = ">=0.3.9"

[tool.poetry.dev-dependencies]
alagitpull = "*"
black = {version="==19.10b0", python="^3.6"}
doc8 = "*"
docutils = "*"
flake8 = "*"
isort = [
  {version="<5", python="<3.6"},
  {version="*", python=">=3.6"}
]
pytest = [
  {version="<4.7.0", python="<3"},
  {version="*", python=">=3"}
]
pathlib2 = {version="<2.3.5", python="<3"}  # Untangle pytest peer-dependency
sphinx = [
  {version="<2", python="<3"},
  {version="*", python=">=3"}
]
sphinx-issues = "*"
twine = "*"
codecov = "*"
coverage = "*"
pytest-cov = [
  {version="<2.10.0", python="<3"},
  {version="*", python=">=3"}
]
