
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-08T02:17:37+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5035a0b5e53ba8194874ddabb041e632162f5419",
 "version": "0.0.1rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
