[tool.poetry]
name = "manage-fastapi"
version = "0.1.1"
description = "Managing FastAPI projects made easy."
authors = ["ycd <yagizcanilbey1903@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/ycd/manage-fastapi"
homepage = "https://github.com/ycd/manage-fastapi"

classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules"
]


[tool.poetry.dependencies]
python = "^3.6"
fastapi= "^0.60.1"
uvicorn = "^0.11.8"
databases = {extras = ["postgresql", "sqlite"], version = "^0.3.2"}
typer = "^0.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"


[tool.poetry.scripts]
manage-fastapi = 'manage_fastapi.main:app'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
