
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-06T21:03:09+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd0d0f2310898b2af76fbe30e8a79c7c4ba74b64",
 "version": "v1.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
