[tool.poetry]
name = "elt-tools-aio"
version = "0.1.0"
description = "Tools for monitoring and troubleshooting ELT arrangements."
authors = ["Dewald Abrie <dewaldabrie@gmail.com>"]
maintainers = ["Dewald Abrie <dewaldabrie@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/dewaldabrie/elt_tools_aio/"
documentation = "https://github.com/dewaldabrie/elt_tools_aio/"
keywords = ["BigQuery",
            "SQL",
            "SQLAlchemy",
            "ETL",
            "AsyncIO",
            "Google Cloud"]

[tool.poetry.dependencies]
python = "^3.7"
sqlalchemy-aio = "*"
pybigquery = "*"
PyMySQL = "*"
psycopg2= "*"
sqlalchemy-redshift= "*"

[tool.poetry.dev-dependencies]
pytest = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
run = "main:main"

[tool.poetry.urls]
issues = "https://github.com/dewaldabrie/elt_tools_aio/issues"
