---
- name: apt-get install git virtualenv python-pip and python-setuptools python-backports.ssl-match-hostname
  apt:
    name: [ git, virtualenv, python-pip, python-setuptools, python-backports.ssl-match-hostname ]
    state: present

- name: chown debian /srv
  file:
    path: /srv
    owner: debian

- name: git clone https://github.com/WeblateOrg/docker-compose
  git:
    repo: 'https://github.com/WeblateOrg/docker-compose'
    version: 62a9ce84d3e818814a92571e3f6ecc54fb46b3e5
    force: yes
    dest: /srv/weblate
  become: False

- name: Copy docker-compose-infrastructure.yml
  template:
    src: docker-compose-infrastructure.yml
    dest: /srv/weblate/docker-compose-infrastructure.yml
    owner: debian
    mode: "0600"

- name: Copy crontab
  template:
    src: crontab
    dest: /srv/weblate/crontab
    owner: debian
    mode: "0600"
  register: crontab

- debug:
    var: crontab

- name: Activate crontab
  shell: crontab /srv/weblate/crontab
  when: crontab is changed
  become: False

- name: (re)create weblate
  shell: |
    docker-compose -f docker-compose-infrastructure.yml up -d
  args:
    chdir: "/srv/weblate"
