
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "aa78460102bcc80bc490d77b4d344c2b8bd8a4e5",
 "version": "2347"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
