conda:
  image: continuumio/miniconda:latest
  tags: 
  - linux

  script:
    - conda env update -q --file=requirements.yml
    - conda env update -q --file=requirements_dev.yml
    - conda info --envs
    - source activate FINE
    - pip install -e .
    - pytest --cov=FINE test/