sudo: false
dist: bionic
language: python
python: 3.7
matrix:
    include:
        - env: TOXENV=py37
        - env: TOXENV=black
        - env: TOXENV=flake8
        - env: TOXENV=docs
        - env: TOXENV=coverage
install:
    - pip install tox
script: tox
