# Generated by Django 2.2.2 on 2019-07-25 13:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Blog Page'},
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.RichTextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Intro'),
        ),
        migrations.AlterField(
            model_name='blogpagegalleryimage',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='blogpagegalleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
    ]
