# Generated by Django 2.2.2 on 2019-07-18 12:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.RichTextField(blank=True, default='')),
                ('partners_groups', wagtail.core.fields.StreamField([('partners_groups', wagtail.core.blocks.StructBlock([('category_name', wagtail.core.blocks.CharBlock(help_text='The category of partner (ex: Institution)', max_length=70, required=False)), ('partners', wagtail.core.blocks.StreamBlock([('partners', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=70)), ('website_url', wagtail.core.blocks.CharBlock(label="Partener's Website")), ('logo', wagtail.images.blocks.ImageChooserBlock())]))]))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
