# Generated by Django 2.2.2 on 2019-07-25 13:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerspage',
            options={'verbose_name': 'Partners'},
        ),
        migrations.AlterField(
            model_name='partnerspage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='partnerspage',
            name='partners_groups',
            field=wagtail.core.fields.StreamField([('partners_groups', wagtail.core.blocks.StructBlock([('category_name', wagtail.core.blocks.CharBlock(help_text='The category of partner (ex: Institution)', label='Category name', max_length=70, required=False)), ('partners', wagtail.core.blocks.StreamBlock([('partners', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(label='Name', max_length=70)), ('website_url', wagtail.core.blocks.CharBlock(label="Partener's Website")), ('logo', wagtail.images.blocks.ImageChooserBlock())]))], label='Partners'))]))], blank=True, null=True, verbose_name="Partners' groups"),
        ),
    ]
