# Generated by Django 3.0.4 on 2020-06-30 09:10

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20190725_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerspage',
            name='partners_groups',
            field=wagtail.core.fields.StreamField([('partners_groups', wagtail.core.blocks.StructBlock([('category_name', wagtail.core.blocks.CharBlock(help_text='The category of partner (ex: Institution)', label='Category name', max_length=100, required=False)), ('partners', wagtail.core.blocks.StreamBlock([('partners', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(label='Name', max_length=100, required=False)), ('website_url', wagtail.core.blocks.CharBlock(label="Partner's Website", required=False)), ('logo', wagtail.images.blocks.ImageChooserBlock(required=False))]))], label='Partners'))]))], blank=True, null=True, verbose_name="Partners' groups"),
        ),
    ]
