<<: &shared
  language_name: Kwak'wala
mappings:
  - display_name: Kwak'wala IPA to English IPA
    mapping: kwk_ipa_to_eng_ipa.json
    in_lang: kwk-ipa
    out_lang: eng-ipa
    case_sensitive: false
    authors:
      - Patrick Littell
    <<: *shared
  - display_name: Kwak'wala (NAPA) to IPA
    mapping: kwk_napa_to_ipa.json
    in_lang: kwk-napa
    out_lang: kwk-ipa
    as_is: false
    authors:
      - Patrick Littell
    <<: *shared
  - display_name: Kwak'wala (U'mista) to IPA
    mapping: kwk_umista_to_ipa.json
    in_lang: kwk-umista
    out_lang: kwk-ipa
    as_is: false
    authors:
      - Patrick Littell
    <<: *shared
  - display_name: Kwak'wala (U'mista) Conversion
    mapping: umista_trans.csv
    in_lang: kwk-umista
    out_lang: kwk-umista-con
    as_is: false
    authors:
      - Fineen Davis
    <<: *shared
  - display_name: Kwak'wala (NAPA) Conversion
    mapping: napa_trans_ubc.csv
    in_lang: kwk-napa-ubc
    out_lang: kwk-napa-ubc-con
    as_is: false
    authors:
      - Fineen Davis
    <<: *shared
  - display_name: Kwak'wala (NAPA) Conversion
    mapping: napa_trans_uvic.csv
    in_lang: kwk-napa-uvic
    out_lang: kwk-napa-uvic-con
    as_is: false
    authors:
      - Fineen Davis
    <<: *shared