# Generated by Django 3.0.4 on 2020-06-16 14:29

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    replaces = [('contact', '0001_initial'), ('contact', '0002_auto_20190719_0803'), ('contact', '0003_auto_20190725_1326'), ('contact', '0004_remove_contactpage_location')]

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Content')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact email')),
                ('opening_hours', wagtail.core.fields.StreamField([('opening_hours', wagtail.core.blocks.StructBlock([('day', wagtail.core.blocks.CharBlock(help_text='example: Monday', label='Day of the week')), ('hours', wagtail.core.blocks.CharBlock(help_text='example: 10h-12h ; 14h-20h', label='Opening hours for the given day'))], icon='time'))], blank=True, null=True, verbose_name='Opening hours')),
                ('opening_hours_free_text', wagtail.core.fields.RichTextField(blank=True, help_text='Put here exceptions like vacation, Bank holidays and so on...', null=True, verbose_name='Opening hours exception or precisions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Contact Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
