# Generated by Django 2.2.2 on 2019-07-25 13:26

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190719_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact Page'},
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='opening_hours',
            field=wagtail.core.fields.StreamField([('opening_hours', wagtail.core.blocks.StructBlock([('day', wagtail.core.blocks.CharBlock(help_text='example: Monday', label='Day of the week')), ('hours', wagtail.core.blocks.CharBlock(help_text='example: 10h-12h ; 14h-20h', label='Opening hours for the given day'))], icon='time'))], blank=True, null=True, verbose_name='Opening hours'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number'),
        ),
    ]
