
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-14T10:36:54-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e10bfe621250e1427fc768edb8f42a1bfc9bd858",
 "version": "2.23.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
