
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-24T11:52:42-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "cadf8d70b5f5025ec817f053cb112b75768d84a1",
 "version": "4.15.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
