
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6b51a8f6630f27f9859659d3adb0c6e249e0f1ce",
 "version": "0.6.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
