language: python
sudo: true
dist: xenial

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
#  - 3.9-dev
#  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.9-dev
  - python: nightly
  - python: 3.8
    arch: arm64
  - python: 3.8
    arch: s390x
  include:
  - python: 3.5
    env: ONLY_BUILTINS=1
    install:
      - pip install .
      - pip install .[test]
  - python: 3.8
    env: PARAMSURVEY_VERBOSE=2 PYTEST_STDERR_VISIBLE=-s
  - python: 3.8
    arch: arm64
#  - python: 3.8
#    arch: s390x

git:
  depth: 99999

install:
  - pip install .
  - pip install .[test]
  - pip install .[ray]
#  - pip install .[mpi]

script:
  - make test_coverage

after_success:
  coveralls
