# coding: utf-8

"""
    Tekton

    Python SDK for Tekton Pipeline  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tekton
from tekton.models.v1beta1_cloud_event_delivery_state import V1beta1CloudEventDeliveryState  # noqa: E501
from tekton.rest import ApiException


class TestV1beta1CloudEventDeliveryState(unittest.TestCase):
    """V1beta1CloudEventDeliveryState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1CloudEventDeliveryState(self):
        """Test V1beta1CloudEventDeliveryState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tekton.models.v1beta1_cloud_event_delivery_state.V1beta1CloudEventDeliveryState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
