[tool.poetry]
name = "MZ_project_gender"
version = "0.1.0"
description = ""
authors = ["mike <mikezhang1970@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
joblib = "^0.16.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
