# coding: utf-8

"""
    VeeRoute.LSS Routing

    VeeRoute.LSS Routing API  # noqa: E501

    The version of the OpenAPI document: 3.3.160640
    Contact: support@veeroute.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import vrt_lss_routing
from vrt_lss_routing.models.routing_task import RoutingTask  # noqa: E501
from vrt_lss_routing.rest import ApiException

class TestRoutingTask(unittest.TestCase):
    """RoutingTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RoutingTask
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = vrt_lss_routing.models.routing_task.RoutingTask()  # noqa: E501
        if include_optional :
            return RoutingTask(
                waypoints = [
                    vrt_lss_routing.models.waypoint.Waypoint(
                        latitude = 55.692789, 
                        longitude = 37.554554, 
                        duration = 15, )
                    ], 
                transport_type = 'CAR', 
                departure_time = '2020-10-21T09:30+03:00', 
                result_timezone = 3, 
                geo_provider = 'OSRM', 
                detail = False
            )
        else :
            return RoutingTask(
                waypoints = [
                    vrt_lss_routing.models.waypoint.Waypoint(
                        latitude = 55.692789, 
                        longitude = 37.554554, 
                        duration = 15, )
                    ],
        )

    def testRoutingTask(self):
        """Test RoutingTask"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
