# coding: utf-8

"""
    Pulp 3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.models.rpm_update_record import RpmUpdateRecord  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException

class TestRpmUpdateRecord(unittest.TestCase):
    """RpmUpdateRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RpmUpdateRecord
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pulpcore.client.pulp_rpm.models.rpm_update_record.RpmUpdateRecord()  # noqa: E501
        if include_optional :
            return RpmUpdateRecord(
                pulp_href = '0', 
                pulp_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                id = '0', 
                updated_date = '0', 
                description = '0', 
                issued_date = '0', 
                fromstr = '0', 
                status = '0', 
                title = '0', 
                summary = '0', 
                version = '0', 
                type = '0', 
                severity = '0', 
                solution = '0', 
                release = '0', 
                rights = '0', 
                pushcount = '0', 
                pkglist = [
                    pulpcore.client.pulp_rpm.models.rpm/update_collection.rpm.UpdateCollection(
                        name = '0', 
                        shortname = '0', 
                        module = pulpcore.client.pulp_rpm.models.module.Module(), 
                        packages = [
                            {
                                'key' : '0'
                                }
                            ], )
                    ], 
                references = [
                    {
                        'key' : '0'
                        }
                    ], 
                reboot_suggested = True
            )
        else :
            return RpmUpdateRecord(
        )

    def testRpmUpdateRecord(self):
        """Test RpmUpdateRecord"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
