# coding: utf-8

"""
    Pulp 3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.models.repository_version import RepositoryVersion  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException

class TestRepositoryVersion(unittest.TestCase):
    """RepositoryVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RepositoryVersion
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pulpcore.client.pulp_rpm.models.repository_version.RepositoryVersion()  # noqa: E501
        if include_optional :
            return RepositoryVersion(
                pulp_href = '0', 
                pulp_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                number = 56, 
                base_version = '0', 
                content_summary = pulpcore.client.pulp_rpm.models.content_summary.Content summary(
                    added = {
                        'key' : {
                            'key' : '0'
                            }
                        }, 
                    removed = {
                        'key' : {
                            'key' : '0'
                            }
                        }, 
                    present = {
                        'key' : {
                            'key' : '0'
                            }
                        }, )
            )
        else :
            return RepositoryVersion(
        )

    def testRepositoryVersion(self):
        """Test RepositoryVersion"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
