# coding: utf-8

"""
    Pulp 3 API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.models.copy import Copy  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException

class TestCopy(unittest.TestCase):
    """Copy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Copy
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pulpcore.client.pulp_rpm.models.copy.Copy()  # noqa: E501
        if include_optional :
            return Copy(
                config = pulpcore.client.pulp_rpm.models.config.Config(), 
                dependency_solving = True
            )
        else :
            return Copy(
                config = pulpcore.client.pulp_rpm.models.config.Config(),
        )

    def testCopy(self):
        """Test Copy"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
