
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-06T02:27:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd9895eb73062315adb025fa5bd38bf48f1dde68",
 "version": "v0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
