
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-11T11:07:01+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2dbec9560e6b715ddb74a4f5b02503de245f9ee",
 "version": "5.21.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
