[tool.poetry]
name = "admin-fastapi"
version = "0.0.1"
description = ""
authors = ["ycd <yagizcanilbey1903@gmail.com>"]



[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
