# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0019_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrobj',
            name='formalname',
            field=models.TextField(db_index=True, verbose_name='\u0424\u043e\u0440\u043c\u0430\u043b\u0438\u0437\u043e\u0432\u0430\u043d\u043d\u043e\u0435 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='addrobj',
            name='offname',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u0444\u0438\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0435 \u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='house',
            name='buildnum',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043a\u043e\u0440\u043f\u0443\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='house',
            name='strucnum',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0441\u0442\u0440\u043e\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='normdoc',
            name='docimgid',
            field=models.TextField(blank=True, null=True, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043e\u0431\u0440\u0430\u0437\u0430 (\u0432\u043d\u0435\u0448\u043d\u0438\u0439 \u043a\u043b\u044e\u0447)'),
        ),
        migrations.AlterField(
            model_name='normdoc',
            name='docnum',
            field=models.TextField(blank=True, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430'),
        ),
    ]
