# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-05-13 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0020_auto_20200513_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='eststatus',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='fias.EstStat', verbose_name='\u041f\u0440\u0438\u0437\u043d\u0430\u043a \u0432\u043b\u0430\u0434\u0435\u043d\u0438\u044f'),
        ),
    ]
