# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-07-22 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0021_auto_20200513_0853'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='addrobj',
            index_together={('aolevel', 'formalname'), ('aolevel', 'shortname'), ('shortname', 'formalname')},
        ),
    ]