# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/3_analyse_intensity.ipynb (unless otherwise specified).

__all__ = ['labels']

# Cell
# export
import pandas
import dotenv
import os
import matplotlib.pyplot as plt
from importlib import reload
import numpy

dotenv.load_dotenv()

labels = ["Bad segmentation", "1 lobe", "2 lobes", "3 lobes", "4 lobes", "Unclear amount of lobes"]


# Cell
from c7m import load_tiff_images, process_segmentation, denoise, focus_stacking
from skimage import img_as_float32
from tqdm.notebook import tqdm, trange
import seaborn
import cv2