#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['click>=7.1.2']

entry_points = \
{'console_scripts': ['fsort = fsort:cli']}

setup(name='fsort',
      version='0.1.1',
      description='Cli util to sort large files',
      author='a.opalev',
      author_email='levisolympus@gmail.com',
      url=None,
      py_modules=['fsort'],
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.5',
     )
