# Generated by Django 2.2.2 on 2019-07-19 12:05

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmixin',
            name='text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Card text content', null=True, verbose_name='Opening hours exception or precisions'),
        ),
    ]
