# Generated by Django 2.2.2 on 2019-07-25 13:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_auto_20190719_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmixin',
            name='buttons',
            field=wagtail.core.fields.StreamField([('buttons', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text="Use this as the text of an external URL or if you want to override the Page's title", label='Link text', max_length=40, required=False)), ('custom_url', wagtail.core.blocks.CharBlock(label='External URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Ignored if the external URL is used', label='Link to an internal page', required=False)), ('extra_url', wagtail.core.blocks.CharBlock(default='', help_text='Use this to optionally append a #hash or querystring to the URL.', label='Append to URL', required=False))], icon='link'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardmixin',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='cardmixin',
            name='text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Card text content', null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='cardmixin',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='linkpage',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Ignored if the external URL is used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='*OR* Link to an internal page'),
        ),
        migrations.AlterField(
            model_name='linkpage',
            name='link_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='link to an external URL'),
        ),
        migrations.AlterField(
            model_name='slidemixin',
            name='buttons',
            field=wagtail.core.fields.StreamField([('buttons', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text="Use this as the text of an external URL or if you want to override the Page's title", label='Link text', max_length=40, required=False)), ('custom_url', wagtail.core.blocks.CharBlock(label='External URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Ignored if the external URL is used', label='Link to an internal page', required=False)), ('extra_url', wagtail.core.blocks.CharBlock(default='', help_text='Use this to optionally append a #hash or querystring to the URL.', label='Append to URL', required=False))], icon='link'))], blank=True, null=True, verbose_name='Buttons'),
        ),
        migrations.AlterField(
            model_name='slidemixin',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='slidemixin',
            name='text',
            field=models.TextField(help_text='Slide text', max_length=200, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='slidemixin',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Title'),
        ),
    ]
