# Generated by Django 3.0.4 on 2020-04-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200407_1328'),
        ('blocks', '0003_auto_20190725_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidemixin',
            name='image',
        ),
        migrations.DeleteModel(
            name='CardMixin',
        ),
        migrations.DeleteModel(
            name='SlideMixin',
        ),
    ]
