---

- name: declare host attribute
  lineinfile:
    line: '  vars.postfix_relay= true'
    insertafter: 'Define host attributes'
    path: /etc/icinga2/zones.d/master/{{ inventory_hostname }}/host.conf
  delegate_to: "{{ item }}"
  loop: "{{groups['icinga-service-group']}}"
  notify: reload icinga2
