# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/filters/http/grpc_web/v3/grpc_web.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class GrpcWeb(betterproto.Message):
    """gRPC Web filter config."""

    pass
