[tool.poetry]
name = "aioerl"
version = "0.0.20200813"
description = "a python library that mimics the philosophy of Erlang's processes with asyncio tasks"
authors = ["Jordi Masip <jordi@masip.cat>"]
license = "GPL-3.0-only"
readme = "README.md"
classifiers = [
    "Framework :: AsyncIO",
    "Development Status :: 3 - Alpha"
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
pytest-asyncio = "^0.14.0"
pytest-cov = "^2.10.0"
black = "^19.10b0"
isort = "^5.4.1"

[tool.isort]
force_single_line = "True"
sections = ["THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER", "STDLIB"]
no_lines_before = ["LOCALFOLDER", "THIRDPARTY", "FIRSTPARTY", "STDLIB"]
force_alphabetical_sort = "True"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
