
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-14T15:50:05-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6deae24560e6076f300fe39c2f6ed532bdb8e988",
 "version": "0.0.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
