[tool.poetry]
name = "veho"
version = "0.0.2"
description = "easy enumerate"
authors = ["Hoyeung Wong <hoyeungw@outlook.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/hoyeungw/intype"
repository = "https://github.com/hoyeungw/intype"
keywords = [
    "list", "array", "vector", "matrix", "1d-list", "2d-list",
    "map", "mapper", "mutate", "zipper", "enumerate", "iterate",
    "entry", "entries", "key-value", "key-value pairs",
    "dict", "object", "json"
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
