name: khmer compatibility tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[test]

      - name: Run tests with latest released khmer
        run: |
          python -m pip install khmer
          python -m pytest -k test_nodegraph --cov=. --cov-report=xml

      - name: Run tests with khmer master tests
        run: |
          python -m pip install -U git+https://github.com/dib-lab/khmer.git#egg=khmer
          python -m pytest -k test_nodegraph --cov=. --cov-report=xml

      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            file: ./coverage.xml
            fail_ci_if_error: true
