name: Metadata checks 

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Trigger new archival in software heritage on new tags
        if: startsWith(github.ref, 'refs/tags/')
        run: curl https://archive.softwareheritage.org/api/1/origin/save/git/url/https://github.com/dib-lab/sourmash.git/
