[tool.poetry]
name = "daml-dit-api"
version = "0.0.2"
description = "DABL Integrations API Package"
authors = ["Mike Schaeffer <mike.schaeffer@digitalasset.com>"]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "*"
dacite = "*"
dazl = "*"

[tool.poetry.dev-dependencies]
mypy = "*"
pytest = "^5.4.3"
pytest-asyncio = "*"
pytest-codestyle = "*"

[tool.poetry.extras]
develop = []

[build-system]
requires = ["poetry_core==1.0.0a8"]
build-backend = "poetry.core.masonry.api"
