name: Tests

on:
  pull_request:
    branches:
    - master
    - develop
  push:
    branches:
    - master
    - develop

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
    - name: Check manifest
      uses: pre-commit/action@v2.0.0
      with:
        extra_args: --hook-stage manual check-manifest

  cmake:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7", "3.5", "3.8"] # Waiting on CPython or PyBind11 fix: , "3.9-dev"]

    name: CMake Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: actions/setup-python@v2
      if: "!endswith(matrix.python-version, 'dev')"
      with:
        python-version: ${{ matrix.python-version }}
    - uses: deadsnakes/action@v1.0.0
      if: "endswith(matrix.python-version, 'dev')"
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python tools
      run: python -m pip install -r dev-requirements.txt

    - name: Configure
      run: mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DBOOST_HISTOGRAM_ERRORS=ON -DPYTHON_EXECUTABLE="$(which python)"

    - name: Build
      run: cmake --build build -j 2

    - name: Test
      working-directory: ./build
      run: python -m pytest

  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==1.5.2 twine

    - name: Build wheel
      run: python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BUILD: cp38-win_amd64 cp27-manylinux_i686 cp37-macosx_x86_64
        CIBW_TEST_EXTRAS: test
        CIBW_TEST_COMMAND: pytest {project}/tests
        CIBW_BUILD_VERBOSITY: 1

    - name: Check wheels
      run: twine check wheelhouse/*
      shell: bash
