
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-17T10:28:57-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "97a13d46a06ffb8e6f583af05d49e1c47ef65dd4",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
