name: pydaymet-dev
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - setuptools
  - py3dep
  - lxml

  - setuptools_scm
  - pytest-cov
  - pytest-xdist
  - pre-commit
  - codecov
  - coverage
