# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/filters/http/cors/v3/cors.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Cors(betterproto.Message):
    """Cors filter config."""

    pass
