
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-08-11T17:47:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "384064510f8959936ff19e7ce4c063f3a9448b5b",
 "version": "0.75.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
