
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-10T12:27:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cdffa1ddc87ff4c1817e9452d3812a2970e1dbf2",
 "version": "v1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
