
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cbeb4ca0c9d0315913062e6d52f37cf5e6592559",
 "version": "2346"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
