[tool.poetry]
name = "fake-keepall"
version = "0.1.2"
description = "Apply the fake `word-break: keep-all;` CSS property to static HTML file"
authors = ["Chanwoong Kim <me@chanwoong.kim>"]
license = "MIT"
classifiers = [
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Text Processing"
]
readme = "README.md"
repository = "https://github.com/kexplo/fake_keepall"
include = ["README.md"]

[tool.poetry.dependencies]
python = "==3.*"
beautifulsoup4 = "^4.9.1"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.2"
flake8-import-order = "^0.18.1"
pyflakes = "^2.2.0"
pytest = "^5.4.3"

[tool.poetry.scripts]
fake-keepall = 'fake_keepall.__init__:cli'

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

