# Generated by Django 2.2.2 on 2019-07-18 12:12

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=40)),
                ('links', wagtail.core.fields.StreamField([('links', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text="Use this as the text of a custom URL or if you want to override the Page's title", label='Link text', max_length=40, required=False)), ('custom_url', wagtail.core.blocks.CharBlock(label='Custom URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Ignored if the custom URL is used', label='Link to an internal page', required=False)), ('extra_url', wagtail.core.blocks.CharBlock(default='', help_text='Use this to optionally append a #hash or querystring to the URL.', label='Append to URL', required=False))], icon='link'))], blank=True, null=True)),
                ('footer', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='site_settings.Footer')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
