# Generated by Django 2.2.2 on 2019-07-25 13:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Footer', 'verbose_name_plural': 'Footer'},
        ),
        migrations.AlterField(
            model_name='footercolumn',
            name='links',
            field=wagtail.core.fields.StreamField([('links', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text="Use this as the text of an external URL or if you want to override the Page's title", label='Link text', max_length=40, required=False)), ('custom_url', wagtail.core.blocks.CharBlock(label='External URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Ignored if the external URL is used', label='Link to an internal page', required=False)), ('extra_url', wagtail.core.blocks.CharBlock(default='', help_text='Use this to optionally append a #hash or querystring to the URL.', label='Append to URL', required=False))], icon='link'))], blank=True, null=True, verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='footercolumn',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Logo'),
        ),
    ]
