# Generated by Django 3.0.4 on 2020-04-15 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('site_settings', '0003_auto_20200402_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSSStyleSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CSS_stylesheet', models.ForeignKey(blank=True, help_text='Upload your own CSS stylesheet to custom the appearance of your website', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='CSS')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'CSS stylesheet',
                'verbose_name_plural': 'CSS stylesheets',
            },
        ),
    ]
