# Generated by Django 3.0.4 on 2020-05-26 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('site_settings', '0005_auto_20200416_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_menu', models.BooleanField(default=False, help_text='Whether to hide the menu bar or not', verbose_name='Hide Menu')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Menu options',
            },
        ),
    ]
