# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/config/ratelimit/v3/rls.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from ...core import v3 as __core_v3__


@dataclass
class RateLimitServiceConfig(betterproto.Message):
    """
    Rate limit :ref:`configuration overview <config_rate_limit_service>`.
    """

    # Specifies the gRPC service that hosts the rate limit service. The client
    # will connect to this cluster when it needs to make rate limit service
    # requests.
    grpc_service: __core_v3__.GrpcService = betterproto.message_field(2)
    # API version for rate limit transport protocol. This describes the rate
    # limit gRPC endpoint and version of messages used on the wire.
    transport_api_version: __core_v3__.ApiVersion = betterproto.enum_field(4)
