# Generated by Django 2.2 on 2020-08-15 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.CharField(blank=True, max_length=160, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('url', models.URLField()),
                ('slug', models.CharField(max_length=5, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('DEACTIVE', 'deactive')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shortener',
                'verbose_name_plural': 'Shorteners',
                'ordering': ['-pk'],
            },
        ),
    ]
