import os

AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
AWS_SECRET_ACCESS_KEY = os.environ["AWS_SECRET_ACCESS_KEY"]
AWS_SQS_SNS_REGION = os.environ["AWS_SQS_SNS_REGION"]
AWS_SQS_SNS_ENDPOINT_URL = os.environ["AWS_SQS_SNS_ENDPOINT_URL"]
