
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-08T09:47:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "567df49a8f478b807a57165a27f1efca588c49f2",
 "version": "1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
