from djangosubscribe.modeladmins.QuickEmailSubscriptionModelAdmin import QuickEmailSubscriptionModelAdmin
from djangosubscribe.modeladmins.BasicInformationModelAdmin import BasicInformationModelAdmin
from djangosubscribe.modeladmins.EducationalInformationModelAdmin import EducaionalInformationModelAdmin
from djangosubscribe.modeladmins.WorkInformationModelAdmin import WorkInformationModelAdmin
from djangosubscribe.modeladmins.ParentalInformationModelAdmin import ParentalInformationModelAdmin
from djangosubscribe.modeladmins.CategoryModelAdmin import CategoryModelAdmin