
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-08-07T12:22:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f819e1f0545b7a00a4ad89e15cbce5861d731ce6",
 "version": "0.50.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
