# Generated by Django 2.2.2 on 2019-07-25 13:26

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('legal_notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalnoticepage',
            name='subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='legalnoticepage',
            name='content',
            field=wagtail.core.fields.RichTextField(verbose_name='Content'),
        ),
    ]
