
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-06T11:41:57+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "56e0a9de8a95870d65e5577923cc618354265447",
 "version": "1.2.6-alpha.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
