
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-08-10T12:00:13+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "635ffdc03c50d182f1269f04bf78534b007ba5de",
 "version": "v0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
