
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-12T10:50:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "02f90aa16fb65a23457dd18980077e9cf9f6e8c0",
 "version": "0.25.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
