#@ load("@ytt:data", "data")
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: #@ data.values.project_name + '-'
spec:
  entrypoint: dag
  templates:
  - name: kedro
    inputs:
      parameters:
      - name: kedro_node
    container:
      image: #@ data.values.image
      command: [sh, -c]
      args: ["kedro run -n '{{inputs.parameters.kedro_node}}'"]
  - name: dag
    dag:
      tasks:
      #@ for/end task in data.values.tasks:
      - name: #@ task.clean_name
        template: kedro
        dependencies:
        #@ for/end dep in task.dep:
        - #@ dep

        arguments:
          parameters:
          - name: kedro_node
            value: #@ task.name
