[package]
name = "sourmash"
version = "0.9.0"
authors = ["Luiz Irber <luiz.irber@gmail.com>"]
description = "MinHash sketches for genomic data"
repository = "https://github.com/dib-lab/sourmash"
keywords = ["minhash", "bioinformatics"]
categories = ["science", "algorithms", "data-structures"]
license = "BSD-3-Clause"
edition = "2018"
readme = "README.md"
autoexamples = false
autobins = false

[lib]
name = "sourmash"
crate-type = ["lib", "staticlib", "cdylib"]
bench = false

[features]
from-finch = ["finch"]
parallel = ["rayon"]

[dependencies]
backtrace = "=0.3.46" # later versions require rust 1.40
byteorder = "1.3.4"
cfg-if = "0.1.10"
failure = "0.1.8"  # can remove after .backtrace() is available in std::error::Error
finch = { version = "0.3.0", optional = true }
fixedbitset = "0.3.0"
log = "0.4.8"
md5 = "0.7.0"
murmurhash3 = "0.0.5"
niffler = { version = "2.2.0", default-features = false, features = [ "gz" ] }
nohash-hasher = "0.2.0"
once_cell = "1.3.1"
rayon = { version = "1.3.0", optional = true }
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
primal-check = "0.2.3"
thiserror = "1.0"
typed-builder = "0.7.0"
getset = "0.1.1"

[target.'cfg(all(target_arch = "wasm32", target_vendor="unknown"))'.dependencies.wasm-bindgen]
version = "0.2.62"
features = ["serde-serialize"]

[target.'cfg(all(target_arch = "wasm32", target_vendor="unknown"))'.dev-dependencies]
wasm-bindgen-test = "0.3.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.assert_cmd]
version = "1.0.1"

[dev-dependencies]
assert_matches = "1.3.0"
criterion = "0.3.2"
predicates = "1.0.4"
proptest = { version = "0.9.6", default-features = false, features = ["std"]}  # Upgrade to 0.10 requires rust 1.39
rand = "0.7.3"
tempfile = "3.1.0"

[dev-dependencies.needletail]
version = "0.4.0"
default-features = false

[[bench]]
name = "index"
harness = false

[[bench]]
name = "compute"
harness = false

[[bench]]
name = "nodegraph"
harness = false
