---
- name: setup DNS client
  hosts: bind-client-group:!external-host
  become: true
  vars:
    dns_a_record: "{{ ansible_hostname }}"
    dns_cname_record: '{{ ansible_hostname | replace("-host","") }}'
    dns_a: "{{ ansible_host }}"

  pre_tasks:
    - name: set A
      nsupdate:
        server: "{{ hostvars['bind-host']['ansible_host'] }}"
        zone: "{{ domain }}"
        record: "{{ dns_a_record }}"
        ttl: 1800
        type: A
        value: "{{ dns_a }}"
      delegate_to: "{{ item }}"
      loop: "{{groups['bind-service-group']}}"

    - name: set CNAME
      nsupdate:
        server: "{{ hostvars['bind-host']['ansible_host'] }}"
        zone: "{{ domain }}"
        record: "{{ dns_cname_record }}"
        ttl: 1800
        type: CNAME
        value: "{{ dns_a_record }}"
      delegate_to: "{{ item }}"
      loop: "{{groups['bind-service-group']}}"

    - debug:
        msg: |
          {{ dns_a_record }} IN A {{ dns_a }}
          {{ dns_cname_record }} IN CNAME {{ dns_a_record }}
