[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool.black]
line-length = 88
skip-string-normalization = true  # wemake-python-styleguide enforces single quotes
target-version = ["py38"]

[tool.poetry]
name = "lalib"
version = "0.1.0"

authors = [
    "Alexander Hess <alexander@webartifex.biz>",
]
description = "A library in core Python to study linear algebra"
keywords = [
    "python",
    "educational",
    "linear-algebra",
]
license = "MIT"

readme = "README.md"
homepage = "https://github.com/webartifex/lalib"
repository = "https://github.com/webartifex/lalib"

[tool.poetry.dependencies]
python = "^3.7"

# A dependency that is in the standard library for Python 3.8+
# does not count against lalib's "only core Python" promise.
importlib_metadata = {version = "^1.7.0", python = "3.7"}

[tool.poetry.dev-dependencies]
# Task Runners
nox = "^2020.5.24"
pre-commit = "^2.6.0"

# Code Formatters
autoflake = "^1.3.1"
black = "^19.10b0"
isort = "^4.3.21" # TODO (isort): not ^5.4.1 due to pylint and wemake-python-styleguide

# Code Linters
flake8 = "^3.8.3"
flake8-annotations = "^2.3.0"
flake8-black = "^0.2.1"
flake8-expression-complexity = "^0.0.8"
flake8-pytest-style = "^1.2.3"
mypy = "^0.782"
pylint = "^2.5.3"
wemake-python-styleguide = "^0.14.1"  # flake8 plug-in

# Test Suite
codecov = "^2.1.8"
coverage = "^5.2.1"
packaging = "^20.4"  # used to test the packaged version
pytest = "^6.0.1"
pytest-cov = "^2.10.0"
xdoctest = {version = "^0.13.0", extras = ["optional"]}

# Documentation
sphinx = "^3.2.0"
sphinx-autodoc-typehints = "^1.11.0"
