from djangosubscribe.modelforms.CategoryModelForm import CategoryModelForm
from djangosubscribe.modelforms.QESMasOverviewModelForm import OverviewModelForm
from djangosubscribe.modelforms.BasicInformationModelForm import BasicInformationModelForm
from djangosubscribe.modelforms.ParentalInformationModelForm import ParentalInformationModelForm
from djangosubscribe.modelforms.WorkInformationModelForm import WorkInformationModelForm
from djangosubscribe.modelforms.EducationalInformationModelForm import EducationalInformationModelForm