[tool.poetry]
name = "django-willing-zg"
version = "0.2.0"
description = ""
readme = "README.md"
authors = ["Bequest, Inc. <oss@willing.com>"]
packages = [
    { include = "willing_zg" },
]

[tool.poetry.dependencies]
python = "^3.7"
django = "^3.0.8"
djangorestframework = "^3.11.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.black]
line-length = 95
target-version = ['py37']
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
