
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-06T03:04:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "71f1fee3c1a3be13793f51939ccf48e8e5d423f0",
 "version": "0.5.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
