image: python:alpine

before_script:
  - apk add --no-cache
      bash
      build-base
      linux-headers
      musl-dev
      libstdc++
      libffi-dev
      libressl-dev
      libxml2-dev
      libxslt-dev
      pcre-dev
      git
      python3-dev
  - pip install --upgrade pip
  - pip install tox;


stages:
  - test

test:
  stage: test
  only:
    - branches
  script:
    - tox -e py3,pep8,cover_report,black_check
