<<: &shared
  language_name: French
mappings:
  - display_name: French to IPA
    in_lang: fra
    out_lang: fra-ipa
    authors:
      - Eric Joanis
    type: mapping
    mapping: fra_to_ipa.csv
    abbreviations: fra_abbs.csv
    as_is: true
    case_sensitive: false
    norm_form: 'NFD'
    <<: *shared
