[tool.poetry]
name = "lonny_common_pg_queue"
version = "0.1.0"
description = "A lightweight distributed queue using a postgres DB."
authors = ["tlonny <t@lonny.io>"]
readme = "README.md"
homepage = "https://lonny.io"
repository = "https://gitlab.com/lonny-common/pg-queue"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pylama = "^7.7.1"
pyflakes = "^2.2.0"
lonny_common_pg = "^0.1.0"
lonny_common_pg_migrate = "^0.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
