
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-08-09T15:40:51+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "14be3f0fc42ed36c65d6b67f0dc5e4300ef284dd",
 "version": "0.50.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
