# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tempfile/%Y/%m/%d/', verbose_name='\u6587\u4ef6')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='\u6587\u4ef6\u540d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_tempfiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u4e34\u65f6\u6587\u4ef6',
                'verbose_name_plural': '\u4e34\u65f6\u6587\u4ef6',
            },
        ),
        migrations.AlterModelOptions(
            name='exceltask',
            options={'verbose_name': 'Excel\u5bfc\u51fa\u4efb\u52a1', 'verbose_name_plural': 'Excel\u5bfc\u51fa\u4efb\u52a1'},
        ),
    ]
