# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-23 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20180312_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempfile',
            options={'ordering': ('-create_time',), 'verbose_name': '\u4e34\u65f6\u6587\u4ef6', 'verbose_name_plural': '\u4e34\u65f6\u6587\u4ef6'},
        ),
    ]
