# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-01 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20180323_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='object_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u540d\u79f0'),
        ),
    ]
