# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-08 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_szuprefix.utils.modelutils


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0004_trash_object_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('object_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u540d\u79f0')),
                ('version', models.PositiveIntegerField()),
                ('json_data', django_szuprefix.utils.modelutils.JSONField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u7248\u672c\u5386\u53f2',
                'verbose_name_plural': '\u7248\u672c\u5386\u53f2',
            },
        ),
        migrations.AlterUniqueTogether(
            name='versionhistory',
            unique_together=set([('content_type', 'object_id', 'version')]),
        ),
    ]
