# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-16 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-create_time',), 'verbose_name': '\u4e8b\u4ef6', 'verbose_name_plural': '\u4e8b\u4ef6'},
        ),
        migrations.AlterField(
            model_name='event',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
