# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-03-02 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20191013_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionhistory',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='versionhistory',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='\u5bf9\u8c61ID'),
        ),
        migrations.AlterField(
            model_name='versionhistory',
            name='version',
            field=models.PositiveIntegerField(verbose_name='\u7248\u672c'),
        ),
    ]
