language: python
matrix:
    include:
        - python: 3.6
        - python: 3.7
        - python: 3.8
install:
    - pip install -U tox-travis
    - pip install -e ."[all]"
    - pip install -e ."[test]"
script:
    - python setup.py test
after_script:
    - bash scripts/deploy.sh
after_success:
    - pip install coveralls
    - coveralls
