
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-12T11:24:28-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "493e1fd603c09eed322adf25612c02f5aafec813",
 "version": "1.11.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
