[tool.poetry]
name = "frattlesnake"
version = "0.1.0"
description = ""
authors = ["Samuel Gaus <sam@gaus.co.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
pyjnius = "^1.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
