__author__ = 'Carlos Vigo <carlosv@phys.ethz.ch>'
__email__ = '<carlosv@phys.ethz.ch>'
__short_author__ = 'Carlos Vigo'
__copyright__ = '2020, Carlos Vigo'
__module_name__ = 'arduino_temperature_sensors.py'
__package_name__ = 'arduino-temperature-sensors'
__project_name__ = 'Arduino Temperature Sensors'
__url__ = 'https://gitlab.ethz.ch/exotic-matter/cw-beam/arduino_temperature_sensors'
__documentation__ = 'https://arduino_temperature_sensors.readthedocs.io'
__version__ = '0.1.0'
__short_version__ = '0.1.0'
__description__ = 'Readout software for the EPIC Arduino Temperature Sensors'

