language: python
python:
  - '3.6'
  - '3.7'

install:
  - python setup.py install

script:
  - pytest .

deploy:
  provider: pypi
  user: jfaria
  password:
    secure: A3DFevZVN/x56uwnOoIaZYoT1NADoLbaFRvidkDGpYQBxhiYS/+1rXarQQ25xnm5FlL0mO3ibF0pAFaKbL2dJFYdNGfDMRsn1mz9zX9z1JNZiBE3MGWFCkQ10v82ZkWmDrife6nyZcxwY6qpbawumtrxMND0AYT5B8/DrXjBOQQ2iYNM+vkdOUSsgQPWuWTHQtcNcQXJtE5TVRGpmZpttLuxQ4b2BqILF57y8mGAQeNvYGc9/SV0mByzVOjrBHioXwx3gt5eDvRgnKpce/4s3QlIDTKa45OQOjhszX5KR7gBuzPZWsHgh4qbDnPSF8RqhoQxSpsZD+nyg03IISr5GKRsHgNKbW5EWTNn5I0bckxAQ86BoKsRobI8t2ipIzXA7cLRhPZMKHFEiM9plAAv+pdx3Ms21iB7vwN5xFssW8apB+SC1hxOOxpOV++jzR47lC9H5fWAz7K8FzmqE2fpZgEPIHQDneDL5OCC62vbw2KK71J4lRPyrboVpIJxMYyV6g7lD6HOPAbzWxdLHeJK1E5Wp74OVOXx/LLDLch7tB+FA+kreTuaZEtW5AJuzzYthyO0nhYRcZRbhxrtaZD+grmprYIdmLw6Nn8CdNSIQazGB/sQuVGyRTZWK2Dj3pmP6U7u3KG0Ta0bb2+Y1KIhST6HD1UBYIsukxLox8LefzY=
  on:
    tags: true
    branch: master
  skip_existing: true
