"""Autogenerated version information file.

Manual changes to this file will be overwritten.

The output of git describe was: ``1.10.0b1``

The derived version is: ``1.10.0b1``
"""
__version__ = '1.10.0b1'
