# coding: utf-8

"""
    Tekton

    Python SDK for Tekton Pipeline  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tekton
from tekton.models.v1beta1_task_resource_binding import V1beta1TaskResourceBinding  # noqa: E501
from tekton.rest import ApiException


class TestV1beta1TaskResourceBinding(unittest.TestCase):
    """V1beta1TaskResourceBinding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1TaskResourceBinding(self):
        """Test V1beta1TaskResourceBinding"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tekton.models.v1beta1_task_resource_binding.V1beta1TaskResourceBinding()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
