
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-16T21:45:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef1f1b8346e22bb435a97f5bc270409a2cf62bc4",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
