[tool.poetry]
name = "tinydb_sqlite"
version = "0.1.1"
description = ""
authors = ["Cologler <skyoflw@gmail.com>"]
license = "MIT"
readme = 'README.md'

[tool.poetry.dependencies]
python = "^3.8"
tinydb = "^4.1.1"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
