
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-08-06T16:36:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bfed73bda97291d047132459b0c5392dd60c981e",
 "version": "0.50.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
