[tool.black]
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = 'black'
add_imports = ['from __future__ import annotations']

[tool.coverage.run]
branch = true
source = ['fourth']

[tool.coverage.report]
omit = ['tests/*']
