# Generated by Django 3.0.8 on 2020-07-24 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='AwardScoreOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Value')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_generic_awards.Award')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectAwardScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('award_score_option_extended', models.TextField(blank=True, verbose_name='Extended score')),
                ('award_addition_info', models.TextField(blank=True, verbose_name='Additional Information')),
                ('award_score_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_generic_awards.AwardScoreOption')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='AwardableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awardablemodels', to='contenttypes.ContentType')),
            ],
        ),
    ]
