# Generated by Django 3.0.8 on 2020-07-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_generic_awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardablemodel',
            name='content_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='awardablemodels', to='contenttypes.ContentType'),
        ),
    ]
