# Generated by Django 3.0.8 on 2020-07-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_generic_awards', '0002_auto_20200724_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardableModel_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'django_generic_awards_awardablemodel_award_for_concrete_model',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='awardablemodel',
            name='award_for_concrete_model',
            field=models.ManyToManyField(related_name='award_to_model', to='django_generic_awards.Award'),
        ),
        migrations.AlterField(
            model_name='objectawardscore',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(awardablemodels__isnull=False), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
