# Generated by Django 3.0.8 on 2020-07-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_generic_awards', '0003_auto_20200724_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwardableModel_link',
        ),
    ]
