# Generated by Django 3.0.8 on 2020-07-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_generic_awards', '0004_delete_awardablemodel_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': 'award', 'verbose_name_plural': 'awards'},
        ),
        migrations.AlterModelOptions(
            name='awardablemodel',
            options={'verbose_name': 'awardable model', 'verbose_name_plural': 'awardable models'},
        ),
        migrations.AlterModelOptions(
            name='awardscoreoption',
            options={'verbose_name': 'award score option', 'verbose_name_plural': 'award score options'},
        ),
        migrations.AlterModelOptions(
            name='objectawardscore',
            options={'verbose_name': 'object award score', 'verbose_name_plural': 'object award scores'},
        ),
        migrations.AddField(
            model_name='award',
            name='help_text',
            field=models.TextField(blank=True, verbose_name='Help text'),
        ),
    ]
