# Generated by Django 3.0.8 on 2020-07-29 08:45

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django_generic_awards.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('django_generic_awards', '0008_auto_20200728_1330'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='award',
            managers=[
                ('award_manager', django_generic_awards.models.AwardManager()),
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterField(
            model_name='award',
            name='site',
            field=models.ForeignKey(default=django_generic_awards.models.get_default_site_id, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='awardablemodel',
            name='site',
            field=models.ForeignKey(default=django_generic_awards.models.get_default_site_id, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='awardscoreoption',
            name='site',
            field=models.ForeignKey(default=django_generic_awards.models.get_default_site_id, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='imageattachment',
            name='site',
            field=models.ForeignKey(default=django_generic_awards.models.get_default_site_id, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='objectawardscore',
            name='site',
            field=models.ForeignKey(default=django_generic_awards.models.get_default_site_id, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
