# Generated by Django 3.0.8 on 2020-07-29 10:14

from django.db import migrations, models
import django.db.models.deletion
import django_generic_awards.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('django_generic_awards', '0009_auto_20200729_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='site',
            field=models.ForeignKey(default=django_generic_awards.models.get_default_site_id, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='awardablemodel',
            name='site',
            field=models.ForeignKey(default=django_generic_awards.models.get_default_site_id, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='awardscoreoption',
            name='site',
            field=models.ForeignKey(default=django_generic_awards.models.get_default_site_id, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='imageattachment',
            name='image',
            field=models.ImageField(upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='imageattachment',
            name='site',
            field=models.ForeignKey(default=django_generic_awards.models.get_default_site_id, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='objectawardscore',
            name='site',
            field=models.ForeignKey(default=django_generic_awards.models.get_default_site_id, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
