# Generated by Django 3.0.8 on 2020-08-04 10:29

import django.contrib.sites.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_generic_awards', '0010_auto_20200729_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardScoreOptionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'award score',
                'verbose_name_plural': 'award scores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_generic_awards.awardscoreoption',),
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterField(
            model_name='award',
            name='help_text',
            field=models.TextField(blank=True, help_text="{} in this string will be replaced with actual Award Score's value", verbose_name='Help text'),
        ),
    ]
