# Generated by Django 3.0.4 on 2020-04-27 08:16

import coldcms.wagtail_customization.mixins
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Subtitle')),
                ('content', wagtail.core.fields.RichTextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Simple page',
            },
            bases=(coldcms.wagtail_customization.mixins.ColdCMSPageMixin, 'wagtailcore.page'),
        ),
    ]
