
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-13T22:12:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a21f3926a3f5523ecd24838082395ccb5b585ff5",
 "version": "5.22.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
