[build-system]
requires = ["poetry>=1.0.0a4"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "rye"
version = "0.6.1"
description = "Concurrent and flexible task runner"
authors = ["Paul Becotte <pjbecotte@gmail.com>"]
license = "MIT"
readme = "README.rst"
repository = "https://gitlab.com/pjbecotte/rye"
packages = [
    {include = "rye", from = "src"}
]
scripts = {rye = "rye.__main__:cli"}


[tool.poetry.dependencies]
python = "^3.6"
toml = "~0.10"
settingscascade = "~0.5.0"
click = "^7.0"
colorama = "~0.4"
virtualenv = "^16.6"
importlib_metadata = "^0.23"
pyyaml = "^5.1.2"

[tool.poetry.dev-dependencies]
black = {version = "^19.10b0", allow-prereleases = true}
# This is a subdep of sphinx, but the current latest package is broken
docutils = "0.15"
isort = "^4.3"
mypy = "^0.710"
pylint = "^2.3"
pytest = "^4.6"
pytest-cov = "^2.7"
sphinx = "^2.1"

[tool.black]
exclude = '\.rye'
