
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-10T09:56:27+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "54bff889a00532d81e439fabd1cb2329cf5cfe04",
 "version": "1.2.6-alpha.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
