[tool.poetry]
name = "jServicePy"
version = "1.0"
description = "API wrapper for jService (comes with a commmand-line game implementation!)"
license = "Public Domain"
authors = ["Kyle Anthony Williams <kyle.anthony.williams2@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/SuperSonicHub1/jServicePy"
repository = "https://github.com/SuperSonicHub1/jServicePy"
keywords = ['jService', 'jeopardy', 'api', 'python3', 'game']
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "License :: Public Domain",
    "Natural Language :: English",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Games/Entertainment",
    "Typing :: Typed"
]
include = ["README.rst", 'LICENSE']


[tool.poetry.dependencies]
python = ">=3.6"
requests = "^2.24.0"
datetime = "^4.3"
typing = "^3.7.4"
argparse = "^1.4.0"

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
