
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-10T11:27:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "80e32c279202b966d01cfa23f2e287c76f65a1ef",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
