
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-13T19:36:02+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "ee3cafc424592cecad0449c915279eeec8159c88",
 "version": "0.0.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
