
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-14T09:50:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2d5c555e71dc5d9559a1a9e3f2a1c2a5e7495084",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
