
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-06T23:48:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "37a2eb9b755d9bc38d00ecad9dc0db151c3e5667",
 "version": "1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
