# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: envoy/extensions/filters/network/wasm/v3/wasm.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .....wasm import v3 as ____wasm_v3__


@dataclass
class Wasm(betterproto.Message):
    """[[#not-implemented-hide:]"""

    # General Plugin configuration.
    config: ____wasm_v3__.PluginConfig = betterproto.message_field(1)
