
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-17T14:50:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e6589ba6fa85f9916b6ff3c148ff1b8935dbd26",
 "version": "0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
