# Generated by Django 2.2.2 on 2019-07-18 12:12

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("blocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePageSmallCards",
            fields=[
                (
                    "cardmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blocks.CardMixin",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="small_cards",
                        to="home.HomePage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False,},
            bases=("blocks.cardmixin",),
        ),
        migrations.CreateModel(
            name="HomePageCarousel",
            fields=[
                (
                    "slidemixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blocks.SlideMixin",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carousel",
                        to="home.HomePage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False,},
            bases=("blocks.slidemixin",),
        ),
        migrations.CreateModel(
            name="HomePageBigCards",
            fields=[
                (
                    "cardmixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blocks.CardMixin",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="big_cards",
                        to="home.HomePage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False,},
            bases=("blocks.cardmixin",),
        ),
    ]
