# Generated by Django 3.0.4 on 2020-04-07 13:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190725_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecarousel',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagecarousel',
            name='slidemixin_ptr',
        ),
        migrations.RemoveField(
            model_name='homepagesmallcards',
            name='cardmixin_ptr',
        ),
        migrations.RemoveField(
            model_name='homepagesmallcards',
            name='page',
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_content_blocks',
            field=wagtail.core.fields.StreamField([('carousel', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title', max_length=60, required=False)), ('text', wagtail.core.blocks.TextBlock(label='Slide text', max_length=200, required=False)), ('buttons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text="Use this as the text of an external URL or if you want to override the Page's title", label='Link text', max_length=40, required=False)), ('custom_url', wagtail.core.blocks.CharBlock(label='External URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Ignored if the external URL is used', label='Link to an internal page', required=False)), ('extra_url', wagtail.core.blocks.CharBlock(default='', help_text='Use this to optionally append a #hash or querystring to the URL.', label='Append to URL', required=False))], icon='link'), label='Buttons')), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))]), icon='image')), ('big_card', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title', max_length=40, required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'hr'], label='Text', required=False)), ('buttons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text="Use this as the text of an external URL or if you want to override the Page's title", label='Link text', max_length=40, required=False)), ('custom_url', wagtail.core.blocks.CharBlock(label='External URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Ignored if the external URL is used', label='Link to an internal page', required=False)), ('extra_url', wagtail.core.blocks.CharBlock(default='', help_text='Use this to optionally append a #hash or querystring to the URL.', label='Append to URL', required=False))], icon='link'), label='Buttons')), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]), icon='form', label='Big cards group')), ('small_card', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title', max_length=40, required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'hr'], label='Text', required=False)), ('buttons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text="Use this as the text of an external URL or if you want to override the Page's title", label='Link text', max_length=40, required=False)), ('custom_url', wagtail.core.blocks.CharBlock(label='External URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Ignored if the external URL is used', label='Link to an internal page', required=False)), ('extra_url', wagtail.core.blocks.CharBlock(default='', help_text='Use this to optionally append a #hash or querystring to the URL.', label='Append to URL', required=False))], icon='link'), label='Buttons')), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]), icon='form', label='Small cards group'))], blank=True, null=True, verbose_name='Content'),
        ),
        migrations.DeleteModel(
            name='HomePageBigCards',
        ),
        migrations.DeleteModel(
            name='HomePageCarousel',
        ),
        migrations.DeleteModel(
            name='HomePageSmallCards',
        ),
    ]
