[tool.poetry]
name = "aryth"
version = "0.0.1"
description = "numerical tools"
authors = ["Hoyeung Wong <hoyeungw@outlook.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/hoyeungw/aryth"
repository = "https://github.com/hoyeungw/aryth"
keywords = [
    "aryth", "numerical", "math", "statistics", "stat",
    "max", "min", "bound",
    "list", "array", "vector", "matrix", "1d-list", "2d-list"
]

[tool.poetry.dependencies]
python = "^3.8"
intype = "^0.0.2"
veho = "^0.0.2"
texting = "^0.0.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
