[tool.poetry]
name = "mstardna"
version = "0.1.1"
description = ""
authors = ["Jinyoung Kim <jinyoung.kim@morningstar.com>"]

[tool.poetry.dependencies]
python = "^3.7"
boto3 = "^1.14.42"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
