[tool.poetry]
name = "tenhoulog"
version = "0.1.1"
description = "utils for tenhou log"
authors = ["kitagawa-hr <kitagawahr@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/kitagawa-hr/tenhoulog"
repository = "https://github.com/kitagawa-hr/tenhoulog"

[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.13.3"
pandas = "^1.1.0"
beautifultable = "^1.0.0"
pydantic = "^1.6.1"
matplotlib = "^3.3.0"
japanize-matplotlib = "^1.1.2"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
flake8 = "^3.8.3"
mypy = "^0.782"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
