[tool.poetry]
name = "limit-coverage"
version = "0.3.1"
description = ""
authors = ["Max W Chase <max.chase@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
limit-coverage = "limit_coverage:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

