
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-14T11:59:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b9a319bc45edd6aba4cb299f6ea078f189bed3ed",
 "version": "1.11.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
