#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['hostlist', 'hostlist.dnsvs']

package_data = \
{'': ['*']}

install_requires = \
['PyYAML',
 'termcolor',
 'requests',
 'cherrypy',
 'GitPython',
 'ansible-cmdb',
 'typing']

entry_points = \
{'console_scripts': ['addhost = hostlist.addhost:main',
                     'buildfiles = hostlist.buildfiles:main',
                     'hostlist-daemon = hostlist.daemon:main']}

setup(name='hostlist',
      version='1.4.4',
      description='Sync hostlist and builds config files for services.',
      author='Robin Roth',
      author_email='robin.roth@kit.edu',
      url='https://github.com/particlekit/hostlist',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.2',
     )
