[tool.poetry]
name = "iart"
version = "1.0.0"
description = "A reporting tool for exporting iAuditor inspections into human readable Excel or CSV files."
authors = ["Edd <edward.abrahamsen-mills@safetyculture.io>"]
packages = [
    { include = "iart" }
]

[tool.poetry.dependencies]
python = "^3.6.1"
requests = "^2.23.0"
unicodecsv = "^0.14.1"
pandas = "^1.0.4"
OrderedDict = "^1.1"
tqdm = "^4.46.1"
xlsxwriter = "^1.2.9"
pyinquirer = "^1.0.3"
dateparser = "^0.7.6"
typer-cli = "^0.0.9"
typer = "^0.2.1"
safetyculture-sdk-python-beta = "^2.1.3"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
black = "^19.10b0"

[tool.poetry.scripts]
iart_export = "iart.main:export"
iart_setup = "iart.main:interactive_setup"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
