# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parsec/core/gui/forms/create_org_second_page_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateOrgSecondPageWidget(object):
    def setupUi(self, CreateOrgSecondPageWidget):
        CreateOrgSecondPageWidget.setObjectName("CreateOrgSecondPageWidget")
        CreateOrgSecondPageWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(CreateOrgSecondPageWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(CreateOrgSecondPageWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_user_email = QtWidgets.QLabel(CreateOrgSecondPageWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_user_email.setFont(font)
        self.label_user_email.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_email.setObjectName("label_user_email")
        self.verticalLayout_5.addWidget(self.label_user_email)
        self.line_edit_user_email = QtWidgets.QLineEdit(CreateOrgSecondPageWidget)
        self.line_edit_user_email.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_user_email.setFont(font)
        self.line_edit_user_email.setPlaceholderText("")
        self.line_edit_user_email.setObjectName("line_edit_user_email")
        self.verticalLayout_5.addWidget(self.line_edit_user_email)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_org_name = QtWidgets.QLabel(CreateOrgSecondPageWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_org_name.setFont(font)
        self.label_org_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_org_name.setObjectName("label_org_name")
        self.verticalLayout_7.addWidget(self.label_org_name)
        self.line_edit_org_name = QtWidgets.QLineEdit(CreateOrgSecondPageWidget)
        self.line_edit_org_name.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_org_name.setFont(font)
        self.line_edit_org_name.setPlaceholderText("")
        self.line_edit_org_name.setObjectName("line_edit_org_name")
        self.verticalLayout_7.addWidget(self.line_edit_org_name)
        self.verticalLayout.addLayout(self.verticalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.check_accept_contract = QtWidgets.QCheckBox(CreateOrgSecondPageWidget)
        self.check_accept_contract.setMinimumSize(QtCore.QSize(0, 0))
        self.check_accept_contract.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.check_accept_contract.setText("")
        self.check_accept_contract.setObjectName("check_accept_contract")
        self.horizontalLayout.addWidget(self.check_accept_contract)
        self.label_2 = QtWidgets.QLabel(CreateOrgSecondPageWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(CreateOrgSecondPageWidget)
        QtCore.QMetaObject.connectSlotsByName(CreateOrgSecondPageWidget)

    def retranslateUi(self, CreateOrgSecondPageWidget):
        _translate = QtCore.QCoreApplication.translate
        CreateOrgSecondPageWidget.setWindowTitle(_translate("CreateOrgSecondPageWidget", "Form"))
        self.label.setText(_translate("CreateOrgSecondPageWidget", "TEXT_ORG_WIZARD_CREATE_ORG_INSTRUCTIONS"))
        self.label_user_email.setText(_translate("CreateOrgSecondPageWidget", "TEXT_LABEL_USER_EMAIL"))
        self.label_org_name.setText(_translate("CreateOrgSecondPageWidget", "TEXT_LABEL_ORG_NAME"))
        self.label_2.setText(_translate("CreateOrgSecondPageWidget", "ACTION_ACCEPT_CONTRACT"))
