
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-13T10:08:39-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9701509a833e45bf0c7c7768ecd7bd6f86339c43",
 "version": "0.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
