
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3a85b3dc9c7b84f41de70b9c9904a35408268d1c",
 "version": "2340"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
