# coding: utf-8

"""
    Tekton

    Python SDK for Tekton Pipeline  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tekton
from tekton.models.v1beta1_task_ref import V1beta1TaskRef  # noqa: E501
from tekton.rest import ApiException


class TestV1beta1TaskRef(unittest.TestCase):
    """V1beta1TaskRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1TaskRef(self):
        """Test V1beta1TaskRef"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tekton.models.v1beta1_task_ref.V1beta1TaskRef()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
