# coding: utf-8

"""
    Tekton

    Python SDK for Tekton Pipeline  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tekton
from tekton.models.v1beta1_pipeline_task_resources import V1beta1PipelineTaskResources  # noqa: E501
from tekton.rest import ApiException


class TestV1beta1PipelineTaskResources(unittest.TestCase):
    """V1beta1PipelineTaskResources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1beta1PipelineTaskResources(self):
        """Test V1beta1PipelineTaskResources"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tekton.models.v1beta1_pipeline_task_resources.V1beta1PipelineTaskResources()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
