# coding: utf-8

"""
    Tekton

    Python SDK for Tekton Pipeline  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tekton
from tekton.models.v1alpha1_pipeline_resource_spec import V1alpha1PipelineResourceSpec  # noqa: E501
from tekton.rest import ApiException


class TestV1alpha1PipelineResourceSpec(unittest.TestCase):
    """V1alpha1PipelineResourceSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1PipelineResourceSpec(self):
        """Test V1alpha1PipelineResourceSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tekton.models.v1alpha1_pipeline_resource_spec.V1alpha1PipelineResourceSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
