[tool.poetry]
name = "kass-flow"
version = "0.1.0"
description = "Send payments to the KASS mobile payment service"
authors = ["Jón Levy <nonni@nonni.cc>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
pylint = "^2.5.3"
black = "^19.10b0"
mypy = "^0.782"
pytest = "^6.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
