
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-06T19:43:57-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "0cda92d50248d177dc7e57d5cf29034d1415b886",
 "version": "0+untagged.17.g0cda92d"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
