# coding: utf-8

"""
    Jobs API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.jobs_api import JobsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.jobs_api.JobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_jobs_list(self):
        """Test case for jobs_list

        """
        pass

    def test_jobs_read(self):
        """Test case for jobs_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
