# Generated by Django 2.2.2 on 2019-07-19 08:03

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
    ]
