# Generated by Django 2.2.2 on 2019-07-25 13:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20190719_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqpage',
            options={'verbose_name': 'FAQ Page'},
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='questions_groups',
            field=wagtail.core.fields.StreamField([('questions_groups', wagtail.core.blocks.StructBlock([('category_name', wagtail.core.blocks.CharBlock(help_text='The type of question (ex: Accessibility, Rules). You can keep this field empty if you only have one category of questions/answers', label='Category name', max_length=70, required=False)), ('questions', wagtail.core.blocks.StreamBlock([('questions', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock(label='Question', max_length=255)), ('answer', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'hr'], label='Answer'))]))], label='Questions'))]))], blank=True, null=True, verbose_name='Questions groups'),
        ),
    ]
