<<: &shared
  language_name: Tsuut'ina
mappings:
  - display_name: Tsuut'ina to IPA
    mapping: srs_to_ipa.json
    in_lang: srs
    out_lang: srs-ipa
    as_is: true
    norm_form: NFD
    case_sensitive: false
    authors:
      - Christopher Cox
    <<: *shared
  - display_name: Tsuut'ina IPA to English IPA
    mapping: srs_ipa_to_eng_ipa.json
    in_lang: srs-ipa
    out_lang: eng-ipa
    norm_form: NFD
    as_is: true
    case_sensitive: false
    authors:
      - Christopher Cox
    <<: *shared
