
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-08-12T18:29:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc756dce5bab1995a8a700066d88d62860fed48d",
 "version": "0.77.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
