
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-12T11:09:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1773d8d00e84b75645b19536b3a2244cbd9478b7",
 "version": "1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
