
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-08-10T18:08:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "22017999b3d4bf7df5990988e4d6b7949a78e63d",
 "version": "0.50.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
