samples:
  {{samples}}
singularity_path_profiler:
  {{singularity_path_profiler}}
singularity_path_snippy:
  {{singularity_path_snippy}}
profiler_threads:
  {{profiler_threads}}
script_path:
  {{script_path}}
final_output:
  {{final_output}}
db_version:
  {{db_version}}
run_species:
  {{run_species}}
kraken_db:
  {{kraken_db}}
kraken_threads:
  {{kraken_threads}}
snippy_threads:
  {{snippy_threads}}
reference:
  {{reference}}
mask:
  {{mask}}
amr_only:
  {{amr_only}}
template_path:
  {{template_path}}
mode:
  {{mode}}
positive_control:
  {{positive_control}}
index:
  {{index}}
min_cov:
  {{min_cov}}
min_aln:
  {{min_aln}}



