name: Release

on:
  push:
    tags: [ '*' ]

jobs:
  release-docker:
    name: Release docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and Push tag and latest
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: konstin2/maturin
          tag_with_ref: true
          tags: latest

  release-crates-io:
    name: Release crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        with:
          command: login ${CRATES_IO_TOKEN}
      - uses: actions-rs/cargo@v1
        with:
          command: publish

