name: Docker test

on: [push, pull_request]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Build Docker container
      run: docker build --cache-from konstin2/maturin -t maturin .
    - name: Test the Docker container
      run: ./test-dockerfile.sh
