name: 🗑 Wipe stale artifacts
on:
  schedule:
  - cron: 37 * * * *  # every hour

jobs:
  cleanup-artifacts:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: 4 days  # Setting this to 0 will delete all artifacts
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        skip-recent: 24
    - name: Mark job as success
      if: failure()
      run: true
