os: linux
dist: xenial
language: python
install:
- pip install --upgrade pip wheel setuptools
- pip install virtualenv tox
before_script:
- sh -c "if [ '$DATABASE_ENGINE' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS
  gdpr_assist_tests;' -U postgres; fi"
- sh -c "if [ '$DATABASE_ENGINE' = 'pgsql' ]; then psql -c 'create database gdpr_assist_tests;'
  -U postgres; fi"
- sh -c "if [ '$DATABASE_ENGINE' = 'mysql' ]; then mysql -e 'create database IF NOT
  EXISTS gdpr_assist_tests'; fi"
script:
- tox

jobs:
  include:

  - python: '3.5'
    env: TOXENV=py35-django2.2

  - python: '3.6'
    env: TOXENV=py36-django2.2
  - python: '3.6'
    env: TOXENV=py36-django3.0
  - python: '3.6'
    env: TOXENV=py36-django3.1

  - python: '3.7'
    env: TOXENV=py37-django2.2
  - python: '3.7'
    env: TOXENV=py37-django3.0
  - python: '3.7'
    env: TOXENV=py37-django3.1

  - python: '3.8'
    env: TOXENV=py38-django2.2 DEPLOY=true
  - python: '3.8'
    env: TOXENV=py38-django2.2 DATABASE_ENGINE=mysql DATABASE_USER=travis
    services:
      - mysql
  - python: '3.8'
    env: TOXENV=py38-django2.2 DATABASE_ENGINE=pgsql DATABASE_USER=postgres
    services:
      - postgresql
  - python: '3.8'
    env: TOXENV=py38-django3.0
  - python: '3.8'
    env: TOXENV=py38-django3.1
  - python: '3.8'
    env: TOXENV=py38-django3.1 DATABASE_ENGINE=mysql DATABASE_USER=travis
    services:
      - mysql
  - python: '3.8'
    env: TOXENV=py38-django3.1 DATABASE_ENGINE=pgsql DATABASE_USER=postgres
    services:
      - postgresql

deploy:
  provider: pypi
  user: wildfish-deployer
  password:
    secure: WA/hOu0PfmH1+qGXTYZXF+NaQDURWbni7ggjWmiuZ/RC/jajsvaTyxTjHyMI8OYfjZebvrPjbNcSRkmYZr2ntplNaNPQBI3yS5HQjjaKtghy2b0wzsxETuvfa78o5WtpIAr4zdXbESW08jBiKEMgYLrBLigAhaVA68sRoZQU6Zk+8R54Qs3HTUqT81nBA8+7+MfqPE2g9EDnzX+b/8LPpOLMINn3KF9jerYbuuXvt2WfjHGZjDExKh1XrZCB5ZCi7vPO7AI2PnBn3afBztCVebsyXaPt3XwX4yt8Sf2D/pzgZ5a1cDgKFlsme1CcrrWCDY25qccFE8SOd5/1WWpF7kkfGysX6A5YBFh6qaKh6OjBEGZkFvXATX3GUzeI4kymERVnDt23/5DdNJEVjVdZOotzF6GwTnn7YMwoGF1oDIkekkmfUEa/QBxgyaZranJADTw+YK0cWxWbCcNutVXgd8zZQZLxg2+zF/KG6kcVuVT2uQBRaI/wiWF7hhueN4kgVtAukGzJdFGLNz6mOFv8sk1kifBanLhY4rdiGiv4YtexpIV4cli+5l948N+ql4NLbcKOUm2W+7jfnYMgo3O/bx6B9Bk8hVMR8Vfdb7j5c3a23i4N/4B6m8qFWEQBZmUXDamAoLXJwvw/Nu9Cu5+sbrwVs1pKuabD+/sExZ0Nroo=
  on:
    tags: true
    repo: wildfish/django-gdpr-assist
    condition: "$DEPLOY = true"
notifications:
  slack:
    secure: KRV4MEqOcyREbCcoE7MabxhmcY2qLe9hgBGHhhBa7oOD3u+RSrxgUfFgrVUOlZ/8jZlW2HdXRQzmvWOya0WjFce00cxwHM/fSi0PETnByF5V/Q+6WwrlWuyI+KxpjwFrQ9awIHuUFNkmeUo6MJBpw0DQNaIdzEaw3AHYbyJMiRETqDeo26kIePMkpKyU8HTD3AzkKrc/EmCI0nTGL6/ftEvasCfzeGZ0oEU/ZvRJkU+3hr+D8OMExM8BoYBHFZY5VIUpdtnHf0tYXaqj+CRj+2GsWH3tLuj/2KUyCOjAew+Mkzra4bz589LQwVuRdOUPtCzJylwaGAuk/ggywUr94f9bddeVZwdB5xqBwGSkgre/5U7hDjGJ2fLK5cw75txxHlLurieNJYw6/sHWpVpxtWM0n7NCP54c6KKO4qWEo5GqY7e05ri6V/m4VKknNPDi6T0WXxXVsasJBfkbbJ1Yos2ibdrgj/7Rrt6hvVwIngQjtvzHqIJIessjXY6c4gN/aY5P9mt9kjscpVurnN8UtS5BPW0HUJsGS+EWK2xi1DzrKkeian/p75ZYpZQK+fXhjGWmA6cUd3ppT+uUDFNwDPril9P9pb4T42xbrs43dxBi/g8LOwcrszu41SWQhfN3/t8QTzMj2Hhiw4qjQHTGo/ahAnLD056btAbsRwBPqJ0=
