
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-11T22:33:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c66aa1ae673abe2df2fa4bc2904d689c36e85f27",
 "version": "0.1.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
