protocol = "gpio-digital-sensor"
doc = """
Daemon to read from gpio pins as digital sensors.
"""
traits = ["has-measure-trigger", "is-sensor", "is-daemon"]

[links]
source = "https://gitlab.com/yaq/yaqd-rpi-gpio/"
bugtracker = "https://gitlab.com/yaq/yaqd-rpi-gpio/-/issues/"
manufacturer = "https://www.raspberrypi.org/"

[config.channels]
type = "map"
values = {"type"= "record", "name"= "pin", "fields"= [{"name"= "pin", "type"= "int"}, {"name"= "pull_up", "type"= "boolean"}]}
