repos:
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.10
  hooks:
  - id: cmake-format
    additional_dependencies: [pyyaml]

- repo: https://github.com/pycqa/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
    exclude: docs/conf.py
    additional_dependencies: [flake8-bugbear, flake8-print]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.782
  hooks:
  - id: mypy
    files: src

- repo: https://github.com/mgedmin/check-manifest
  rev: "0.42"
  hooks:
  - id: check-manifest
    stages: [manual]

- repo: local
  hooks:
  - id: docker-clang-format
    name: Docker Clang Format
    language: docker_image
    types:
    - c++
    entry: unibeautify/clang-format:latest
    args:
    - -style=file
    - -i
