---
- name: install pad
  hosts: pad-service-group
  become: true

  pre_tasks:

    - name: set CNAME
      nsupdate:
        server: "{{ hostvars['bind-host']['ansible_host'] }}"
        zone: "{{ domain }}"
        record: "pad.{{ domain }}."
        ttl: 1800
        type: CNAME
        value: "website-host.{{ domain }}."
      delegate_to: bind-host

  roles:
    - role: pad

    - role: enough-nginx
      vars:
        enough_nginx_reverse_proxy: 127.0.0.1:9001
        enough_nginx_fqdn: "{{ pad_vhost_fqdn }}"

    - role: certificate
      vars:
        certificate_fqdn: "{{ pad_vhost_fqdn }}"
        certificate_installer: nginx

    - role: monitor_http_vhost
      http_vhost_https: true
      http_vhost_name: Pad
      http_vhost_fqdn: "{{ pad_vhost_fqdn }}"
      http_vhost_uri: "/"
      http_vhost_string: "Etherpad"
