
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-06T13:22:41-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "97009f368d77409805ee36bc53793e9e7d3b1cf0",
 "version": "1.2.6-alpha.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
