---
- import_playbook: "{{ '$SHARE_DIR/enough-before-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/weblate/weblate-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/gitlab/gitlab-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/gitlab/gitlab-ci-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/packages/packages-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/packages/enough-android-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/chat/chat-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/cloud/cloud-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/enough/enough-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/website/website-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/forum/forum-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/api/api-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/openvpn/openvpn-server-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/playbooks/openvpn/openvpn-client-playbook.yml' | expandvars }}"
- import_playbook: "{{ '$SHARE_DIR/enough-after-playbook.yml' | expandvars }}"
