# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-26 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_event', '0004_auto_20200202_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='typeevent',
            options={},
        ),
    ]
